---
output:
  pdf_document: default
  html_document: default
---
# (PART\*) Teil 1 {-}

# Einführung

**Kognitive Lernziele dieser Lehrveranstaltung:**

> Sie sind in der Lage, 
> -	Besonderheiten von R und Konzepte (wie z.B. Recycling und Coercion) zu definieren, zu erklären, zu erkennen, anzuwenden und zu beurteilen.
> -	in R bereits implementierte Funktionen zu untersuchen (z.B. mithilfe von Manual-Einträgen), anzuwenden und diese in eigenen Code zu integrieren.
> -	R-Code wie z.B. Funktionen zu erklären, zu modifizieren, zu analysieren, zu bewerten und selbst zu erschaffen. 
Dazu gehören u.a.

>	    + Datentypen (z.B. numerische und binäre Werte, Zeichenketten),

>     +	Datenstrukturen (Vektoren, Data Frames, Listen, Matrizen, Arrays, Faktoren, etc.), 

>     + Kontrollstrukturen (Bedingungen und Schleifen) und

>     + die Visualisierung von Ergebnissen (mithilfe von Base-R sowie ggplot2).
> -	mithilfe von R Datensätze zu importieren, zu filtern, zu untersuchen, zu analysieren, zu manipulieren und zu speichern (z.B. mithilfe des R-Pakets dplyr).
> -	R als Tool für statistische Auswertungen und Untersuchungen zu nutzen.

 
## Zielgruppe

Dieses Skript richtet sich an die Studierenden des berufsbegleitenden Masterstudiums der FH-Südwestfalen am Standort Meschede. Neben Grundkenntnissen in der Informatik werden solide Kenntnisse einer imperativen Programmiersprache sowie erste grundlegende Kenntnisse in einer objektorientierten Programmiersprache vorausgesetzt. 

Vorausgesetzt werden:

- Grundkenntnisse in der Informatik
- solide Kenntnisse einer imperativen Programmiersprache (wie C, C#, Java oder Python)
- erste grundlegende Kenntnisse in einer objektorientierten Programmiersprache (wie C++ oder Java)

Insbesondere werden grundlegende und in allen imperativen Programmiersprachen zu findende Konzepte wie Variablen und Funktionen vorausgesetzt ebenso wie Kenntnisse über Kontrollstrukturen wie Verzweigungen und Schleifen.

Im Folgenden werden wir oft Vergleiche zu den Programmiersprachen C und C++ ziehen; daher sind Kenntnisse in C und C++ hilfreich, aber nicht zwingend notwendig. Außerdem gehen wir davon aus, dass die Studierenden in der Lage sind, englische Fachtexte zu lesen.

## Überblick

Da es viel gute Quellen und ausführliche Informationen im Internet über R gibt, wollen wir an dieser Stelle auf einen allgemeinen Überblick über die Programmiersprache R verzichten. Stattdessen sollen Sie folgende Teile des [Wikipedia-Artikels „R (Programmiersprache)“](https://de.wikipedia.org/wiki/R_(Programmiersprache)) lesen:

-	von Anfang bis zum Zitat von John M. Chambers
  	„Um Berechnungen in R zu verstehen sind zwei Sätze hilfreich: 
 	 Alles, was existiert, ist ein Objekt. 
  	 Alles, was passiert, ist ein Funktionsaufruf“ 
im Beginn des Abschnitts „Programmierparadigmen“
- der Abschnitt „Pakete“
- der Abschnitt „Unterstützung durch Stiftungen“
-	der Abschnitt „Rezeption“

Danach sollen Sie Übungsfragen (siehe unten) beantworten. Nur ein Teil der Antworten ergibt sich allerdings direkt aus dem Wikipedia-Artikel; für den Rest sind grundlegende Informatikkenntnisse gefragt, die Sie hoffentlich im Bachelorstudium erworben haben.

## Software

Neben dem Softwarepaket R werden wir auch RStudio intensiv benutzen. RStudio (genauer RStudio Desktop) ist eine integrierte Entwicklungsumgebung, die wie R als Open Source Lizenz zur Verfügung steht. Insgesamt gehen wir also davon aus, dass Sie für diese Veranstaltung folgende Softwarepakete auf Ihrem persönlich verfügbaren Rechner installieren: 

R (aktuellste Version):

-	Installationsquelle: https://cran.rstudio.com/
-	Installieren Sie eine dem Betriebssystem entsprechende vorkompilierte Binär-Distribution („precompiled binary distribution“). Unter Windows brauchen Sie lediglich die „base distribution“
-	Wählen Sie die 64-bit-Version, wenn Sie ein 64-bit Betriebssystem benutzen

RStudio Desktop (aktuellste Version):

-	Installationsquelle: https://www.rstudio.com/products/rstudio/download/
- plus verschiedenen Packages, auf die wir weiter unten eingehen werden 

Im Verlauf dieses Moduls werden zusätzlich unterschiedliche Packages benötigt. R benutzt sogenannte Pakete (packages), um thematisch zusammengehörende Software zu bündeln. Pakete sind vergleichbar mit Bibliotheken in anderen Programmiersprachen. Einige Pakete werden je nach Konfiguration automatisch geladen wie zum Beispiel das base-Paket. Pakete werden in bestimmten Verzeichnissen gespeichert. Der R-Befehl `.libPaths()` listet die entsprechenden Verzeichnisse auf. Abhängig vom benutzten Rechner könnte eine Ausgabe wie folgt aussehen (eingegeben in RStudio im Konsolen-Bereich, siehe weiter unten):

```{r}
.libPaths()
```

Aus Zeit- und Speichergründen werden aber nicht alle verfügbaren Pakete beim Start von R geladen. Später werden wir sehen, wie bei Bedarf neue Pakete installiert und geladen werden können.

## Übungen {-}

Beantworten Sie folgenden Fragen:

-	Wird R interpretiert oder kompiliert?
-	Was ist der Unterschied zwischen einem Interpreter und einem Compiler? Erläutern Sie Vor- und Nachteile [@Willms2009, Abschnitte 1.2.1--3]. 
-	Nennen Sie populäre Programmiersprachen, die kompiliert bzw. interpretiert werden.
-	Was ist ein JIT-Compiler?
-	Gibt es für R einen JIT-Compiler? 
-	Ist R Open Source?
-	Welche Lizenzkosten entstehen?
-	Was ist RStudio?
-	Was ist eine integrierte Entwicklungsumgebung (IDE)? 
-	Nennen Sie Beispiele populärer Entwicklungsumgebungen, z. B. für C und C++.
-	Was ist Scheme?
-	Was ist S?
-	Ist R für alle populären Desktop-Betriebssysteme verfügbar?
-	Was sind die Vorteile von R?
-	Was ist in R ein Paket? Paket ist hier die deutsche Übersetzung für welchen englischen Begriff?


