<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Erste Schritte | Statistical Programming</title>
  <meta name="description" content="Chapter 2 Erste Schritte | Statistical Programming Course Notes" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Erste Schritte | Statistical Programming" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Chapter 2 Erste Schritte | Statistical Programming Course Notes" />
  <meta name="github-repo" content="bchwtz/bchwtz-rprg" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Erste Schritte | Statistical Programming" />
  
  <meta name="twitter:description" content="Chapter 2 Erste Schritte | Statistical Programming Course Notes" />
  

<meta name="author" content="Benjamin Buchwitz" />


<meta name="date" content="2025-08-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="einführung.html"/>
<link rel="next" href="chap3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><b>Statistical Programming</b></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="part"><span><b>Teil 1</b></span></li>
<li class="chapter" data-level="1" data-path="02-firststeps.html"><a href="#einf%C3%BChrung"><i class="fa fa-check"></i><b>1</b> Einführung</a>
<ul>
<li class="chapter" data-level="1.1" data-path="einführung.html"><a href="einführung.html"><i class="fa fa-check"></i><b>1.1</b> Zielgruppe</a></li>
<li class="chapter" data-level="1.2" data-path="02-firststeps.html"><a href="#%C3%BCberblick"><i class="fa fa-check"></i><b>1.2</b> Überblick</a></li>
<li class="chapter" data-level="1.3" data-path="einführung.html"><a href="einführung.html#software"><i class="fa fa-check"></i><b>1.3</b> Software</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen"><i class="fa fa-check"></i>Übungen</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ersteschritte.html"><a href="ersteschritte.html"><i class="fa fa-check"></i><b>2</b> Erste Schritte</a>
<ul>
<li class="chapter" data-level="2.1" data-path="02-firststeps.html"><a href="#numerische-ausdr%C3%BCcke"><i class="fa fa-check"></i><b>2.1</b> Numerische Ausdrücke</a></li>
<li class="chapter" data-level="2.2" data-path="ersteschritte.html"><a href="ersteschritte.html#variablen"><i class="fa fa-check"></i><b>2.2</b> Variablen</a></li>
<li class="chapter" data-level="2.3" data-path="ersteschritte.html"><a href="ersteschritte.html#vektoren"><i class="fa fa-check"></i><b>2.3</b> Vektoren</a></li>
<li class="chapter" data-level="2.4" data-path="ersteschritte.html"><a href="ersteschritte.html#recycling"><i class="fa fa-check"></i><b>2.4</b> Recycling</a></li>
<li class="chapter" data-level="2.5" data-path="ersteschritte.html"><a href="ersteschritte.html#rstudio"><i class="fa fa-check"></i><b>2.5</b> RStudio</a></li>
<li class="chapter" data-level="2.6" data-path="ersteschritte.html"><a href="ersteschritte.html#demos"><i class="fa fa-check"></i><b>2.6</b> Demos</a></li>
<li class="chapter" data-level="2.7" data-path="ersteschritte.html"><a href="ersteschritte.html#skripte"><i class="fa fa-check"></i><b>2.7</b> Skripte</a></li>
<li class="chapter" data-level="2.8" data-path="02-firststeps.html"><a href="#einf%C3%BChrung-in-die-entwicklungsumgebung-von-r-fortgeschritten"><i class="fa fa-check"></i><b>2.8</b> Einführung in die Entwicklungsumgebung von R (fortgeschritten)</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-1"><i class="fa fa-check"></i>Übungen</a>
<ul>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-1"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-2"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-3"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-4"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-5"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#aufgabe-6"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="ersteschritte.html"><a href="ersteschritte.html#kurzzusammenfassung"><i class="fa fa-check"></i>Kurzzusammenfassung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap3.html"><a href="chap3.html"><i class="fa fa-check"></i><b>3</b> Kontrollstrukturen und Funktionen</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap3.html"><a href="chap3.html#namen-und-objekte-ein-erster-vergleich-mit-c-und-c"><i class="fa fa-check"></i><b>3.1</b> Namen und Objekte: Ein erster Vergleich mit C und C++</a></li>
<li class="chapter" data-level="3.2" data-path="chap3.html"><a href="chap3.html#funktionen"><i class="fa fa-check"></i><b>3.2</b> Funktionen</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="chap3.html"><a href="chap3.html#benannte-und-optionale-argumente"><i class="fa fa-check"></i><b>3.2.1</b> Benannte und optionale Argumente</a></li>
<li class="chapter" data-level="3.2.2" data-path="chap3.html"><a href="chap3.html#call-by-value-und-copy-on-modify"><i class="fa fa-check"></i><b>3.2.2</b> Call-by-value und Copy-on-modify</a></li>
<li class="chapter" data-level="3.2.3" data-path="chap3.html"><a href="chap3.html#keine-zeiger-und-kein-call-by-reference"><i class="fa fa-check"></i><b>3.2.3</b> Keine Zeiger und kein Call-by-reference</a></li>
<li class="chapter" data-level="3.2.4" data-path="chap3.html"><a href="chap3.html#operator-versus-funktionsaufruf"><i class="fa fa-check"></i><b>3.2.4</b> Operator versus Funktionsaufruf</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="chap3.html"><a href="chap3.html#kontrollstrukturen"><i class="fa fa-check"></i><b>3.3</b> Kontrollstrukturen</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="chap3.html"><a href="chap3.html#verzweigung-if-else"><i class="fa fa-check"></i><b>3.3.1</b> Verzweigung: <code>if-else</code></a></li>
<li class="chapter" data-level="3.3.2" data-path="chap3.html"><a href="chap3.html#verzweigung-ifelse"><i class="fa fa-check"></i><b>3.3.2</b> Verzweigung: <code>ifelse</code></a></li>
<li class="chapter" data-level="3.3.3" data-path="chap3.html"><a href="chap3.html#schleife-while-und-repeat"><i class="fa fa-check"></i><b>3.3.3</b> Schleife: <code>while</code> und <code>repeat</code></a></li>
<li class="chapter" data-level="3.3.4" data-path="chap3.html"><a href="chap3.html#schleife-for"><i class="fa fa-check"></i><b>3.3.4</b> Schleife: <code>for</code></a></li>
<li class="chapter" data-level="3.3.5" data-path="chap3.html"><a href="chap3.html#mehrfachzweigung-switch"><i class="fa fa-check"></i><b>3.3.5</b> Mehrfachzweigung: <code>switch</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-2"><i class="fa fa-check"></i>Übungen</a>
<ul>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-1-1"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-2-1"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-3-1"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-4-1"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-5-1"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-6-1"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-7"><i class="fa fa-check"></i>Aufgabe 7</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#aufgabe-8"><i class="fa fa-check"></i>Aufgabe 8</a></li>
<li class="chapter" data-level="" data-path="chap3.html"><a href="chap3.html#kurzzusammenfassung-1"><i class="fa fa-check"></i>Kurzzusammenfassung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html"><i class="fa fa-check"></i><b>4</b> Homogene Datenstrukturen</a>
<ul>
<li class="chapter" data-level="4.1" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#wichtige-eigenschaften-von-objekten"><i class="fa fa-check"></i><b>4.1</b> Wichtige Eigenschaften von Objekten</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#typeof"><i class="fa fa-check"></i><b>4.1.1</b> <code>typeof()</code></a></li>
<li class="chapter" data-level="4.1.2" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#length"><i class="fa fa-check"></i><b>4.1.2</b> <code>length()</code></a></li>
<li class="chapter" data-level="4.1.3" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#attribute"><i class="fa fa-check"></i><b>4.1.3</b> Attribute</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#atomicvector"><i class="fa fa-check"></i><b>4.2</b> (Atomic) Vector</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#vektorindizierung"><i class="fa fa-check"></i><b>4.2.1</b> Filter und Vektor-Indizierung</a></li>
<li class="chapter" data-level="4.2.2" data-path="02-firststeps.html"><a href="#elemente-einf%C3%BCgen"><i class="fa fa-check"></i><b>4.2.2</b> Elemente einfügen</a></li>
<li class="chapter" data-level="4.2.3" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#test-auf-gleichheit"><i class="fa fa-check"></i><b>4.2.3</b> Test auf Gleichheit</a></li>
<li class="chapter" data-level="4.2.4" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#elementnamen"><i class="fa fa-check"></i><b>4.2.4</b> Elementnamen</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#matrix-und-array"><i class="fa fa-check"></i><b>4.3</b> Matrix und Array</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="02-firststeps.html"><a href="#matrizen-einf%C3%BCgen"><i class="fa fa-check"></i><b>4.3.1</b> Matrizen einfügen</a></li>
<li class="chapter" data-level="4.3.2" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#indizierung"><i class="fa fa-check"></i><b>4.3.2</b> Indizierung</a></li>
<li class="chapter" data-level="4.3.3" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#zeilen--und-spaltennamen"><i class="fa fa-check"></i><b>4.3.3</b> Zeilen- und Spaltennamen</a></li>
<li class="chapter" data-level="4.3.4" data-path="02-firststeps.html"><a href="#einf%C3%BCgen-und-l%C3%B6schen-von-zeilen-und-spalten"><i class="fa fa-check"></i><b>4.3.4</b> Einfügen und Löschen von Zeilen und Spalten</a></li>
<li class="chapter" data-level="4.3.5" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#matrixoperationen"><i class="fa fa-check"></i><b>4.3.5</b> Matrixoperationen</a></li>
<li class="chapter" data-level="4.3.6" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#lineare-gleichungssysteme"><i class="fa fa-check"></i><b>4.3.6</b> Lineare Gleichungssysteme</a></li>
<li class="chapter" data-level="4.3.7" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#eigenwerte-und-eigenvektoren"><i class="fa fa-check"></i><b>4.3.7</b> Eigenwerte und Eigenvektoren</a></li>
<li class="chapter" data-level="4.3.8" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#apply"><i class="fa fa-check"></i><b>4.3.8</b> <code>apply()</code></a></li>
<li class="chapter" data-level="4.3.9" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#array"><i class="fa fa-check"></i><b>4.3.9</b> Array</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-3"><i class="fa fa-check"></i>Übungen</a>
<ul>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-1-2"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-2-2"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-3-2"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-4-2"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-5-2"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-6-2"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-7-1"><i class="fa fa-check"></i>Aufgabe 7</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-8-1"><i class="fa fa-check"></i>Aufgabe 8</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-9"><i class="fa fa-check"></i>Aufgabe 9</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-10"><i class="fa fa-check"></i>Aufgabe 10</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-11"><i class="fa fa-check"></i>Aufgabe 11</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-12"><i class="fa fa-check"></i>Aufgabe 12</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-13"><i class="fa fa-check"></i>Aufgabe 13</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-14"><i class="fa fa-check"></i>Aufgabe 14</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-15"><i class="fa fa-check"></i>Aufgabe 15</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-16"><i class="fa fa-check"></i>Aufgabe 16</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-17"><i class="fa fa-check"></i>Aufgabe 17</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-18"><i class="fa fa-check"></i>Aufgabe 18</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-19"><i class="fa fa-check"></i>Aufgabe 19</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-20"><i class="fa fa-check"></i>Aufgabe 20</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-21"><i class="fa fa-check"></i>Aufgabe 21</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#aufgabe-22"><i class="fa fa-check"></i>Aufgabe 22</a></li>
<li class="chapter" data-level="" data-path="homogenedatenstrukturen.html"><a href="homogenedatenstrukturen.html#kurzzusammenfassung-2"><i class="fa fa-check"></i>Kurzzusammenfassung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap5.html"><a href="chap5.html"><i class="fa fa-check"></i><b>5</b> Weitere Datenstrukturen</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap5.html"><a href="chap5.html#listen"><i class="fa fa-check"></i><b>5.1</b> Listen</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="chap5.html"><a href="chap5.html#erzeugung-von-listen-und-indexierung"><i class="fa fa-check"></i><b>5.1.1</b> Erzeugung von Listen und Indexierung</a></li>
<li class="chapter" data-level="5.1.2" data-path="02-firststeps.html"><a href="#listen-%C3%A4ndern"><i class="fa fa-check"></i><b>5.1.2</b> Listen ändern</a></li>
<li class="chapter" data-level="5.1.3" data-path="chap5.html"><a href="chap5.html#vergleich-liste-versus-vektor"><i class="fa fa-check"></i><b>5.1.3</b> Vergleich: Liste versus Vektor</a></li>
<li class="chapter" data-level="5.1.4" data-path="chap5.html"><a href="chap5.html#lapply-und-sapply"><i class="fa fa-check"></i><b>5.1.4</b> <code>lapply()</code> und <code>sapply()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="chap5.html"><a href="chap5.html#factor"><i class="fa fa-check"></i><b>5.2</b> Factor</a></li>
<li class="chapter" data-level="5.3" data-path="chap5.html"><a href="chap5.html#data-frame"><i class="fa fa-check"></i><b>5.3</b> Data Frame</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="chap5.html"><a href="chap5.html#dataframeerzeugen"><i class="fa fa-check"></i><b>5.3.1</b> Data Frame erzeugen</a></li>
<li class="chapter" data-level="5.3.2" data-path="chap5.html"><a href="chap5.html#der-indexoperator"><i class="fa fa-check"></i><b>5.3.2</b> Der Indexoperator</a></li>
<li class="chapter" data-level="5.3.3" data-path="chap5.html"><a href="chap5.html#apply-1"><i class="fa fa-check"></i><b>5.3.3</b> <code>apply()</code></a></li>
<li class="chapter" data-level="5.3.4" data-path="02-firststeps.html"><a href="#filtern-einf%C3%BCgen-und-l%C3%B6schen"><i class="fa fa-check"></i><b>5.3.4</b> Filtern, Einfügen und Löschen</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen---teil-1"><i class="fa fa-check"></i>Übungen - Teil 1</a>
<ul>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-1-3"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-2-3"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-3-3"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-4-3"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-5-3"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-6-3"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-7-2"><i class="fa fa-check"></i>Aufgabe 7</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-8-2"><i class="fa fa-check"></i>Aufgabe 8</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-9-1"><i class="fa fa-check"></i>Aufgabe 9</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-10-1"><i class="fa fa-check"></i>Aufgabe 10</a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen---teil-2"><i class="fa fa-check"></i>Übungen - Teil 2</a>
<ul>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-11-1"><i class="fa fa-check"></i>Aufgabe 11</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-12-1"><i class="fa fa-check"></i>Aufgabe 12</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#aufgabe-13-1"><i class="fa fa-check"></i>Aufgabe 13</a></li>
<li class="chapter" data-level="" data-path="chap5.html"><a href="chap5.html#kurzzusammenfassung-3"><i class="fa fa-check"></i>Kurzzusammenfassung</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="datenvisualisierung-mit-ggplot2.html"><a href="datenvisualisierung-mit-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Datenvisualisierung mit <code>ggplot2</code></a>
<ul>
<li class="chapter" data-level="6.1" data-path="datenvisualisierung-mit-ggplot2.html"><a href="datenvisualisierung-mit-ggplot2.html#erste-beispiele"><i class="fa fa-check"></i><b>6.1</b> Erste Beispiele</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="02-firststeps.html"><a href="#beispiel-%C3%A4sthetische-eigenschaften-aesthetic-festlegen"><i class="fa fa-check"></i><b>6.1.1</b> Beispiel: Ästhetische Eigenschaften (aesthetic) festlegen</a></li>
<li class="chapter" data-level="6.1.2" data-path="02-firststeps.html"><a href="#beispiel-%C3%A4sthetische-eigenschaften-aesthetic-f%C3%BCr-geom_point"><i class="fa fa-check"></i><b>6.1.2</b> Beispiel: Ästhetische Eigenschaften (aesthetic) für <code>geom_point()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="datenvisualisierung-mit-ggplot2.html"><a href="datenvisualisierung-mit-ggplot2.html#statistische-transformation"><i class="fa fa-check"></i><b>6.2</b> Statistische Transformation</a></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-4"><i class="fa fa-check"></i>Übungen</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>7</b> Data Transformation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="data-transformation.html"><a href="data-transformation.html#der-datensatz-flights"><i class="fa fa-check"></i><b>7.1</b> Der Datensatz <code>flights</code></a></li>
<li class="chapter" data-level="7.2" data-path="data-transformation.html"><a href="data-transformation.html#dplyr-grundlagen"><i class="fa fa-check"></i><b>7.2</b> <code>dplyr</code>-Grundlagen</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="02-firststeps.html"><a href="#filter-zeilen-ausw%C3%A4hlen"><i class="fa fa-check"></i><b>7.2.1</b> <code>filter()</code>: Zeilen auswählen</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-transformation.html"><a href="data-transformation.html#arrange-nach-spalten-sortieren"><i class="fa fa-check"></i><b>7.2.2</b> <code>arrange()</code>: nach Spalten sortieren</a></li>
<li class="chapter" data-level="7.2.3" data-path="02-firststeps.html"><a href="#select-spalten-ausw%C3%A4hlen"><i class="fa fa-check"></i><b>7.2.3</b> <code>select()</code>: Spalten auswählen</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-transformation.html"><a href="data-transformation.html#mutate-neue-spalten-erzeugen"><i class="fa fa-check"></i><b>7.2.4</b> <code>mutate()</code>: neue Spalten erzeugen</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-transformation.html"><a href="data-transformation.html#summarize-spalten-verdichten"><i class="fa fa-check"></i><b>7.2.5</b> <code>summarize()</code>: Spalten verdichten</a></li>
<li class="chapter" data-level="7.2.6" data-path="data-transformation.html"><a href="data-transformation.html#der-pipe-operator"><i class="fa fa-check"></i><b>7.2.6</b> Der Pipe-Operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="7.2.7" data-path="data-transformation.html"><a href="data-transformation.html#gruppierungen-mit-group_by"><i class="fa fa-check"></i><b>7.2.7</b> Gruppierungen mit <code>group_by()</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-5"><i class="fa fa-check"></i>Übungen</a>
<ul>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-1-4"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-2-4"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-3-4"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-4-4"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-5-4"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-6-4"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-7-3"><i class="fa fa-check"></i>Aufgabe 7</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-8-3"><i class="fa fa-check"></i>Aufgabe 8</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-9-2"><i class="fa fa-check"></i>Aufgabe 9</a></li>
<li class="chapter" data-level="" data-path="data-transformation.html"><a href="data-transformation.html#aufgabe-10-2"><i class="fa fa-check"></i>Aufgabe 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chap8.html"><a href="chap8.html"><i class="fa fa-check"></i><b>8</b> Exploratory data analysis (EDA)</a>
<ul>
<li class="chapter" data-level="" data-path="chap8.html"><a href="chap8.html#der-datensatz-diamonds"><i class="fa fa-check"></i>Der Datensatz <code>diamonds</code></a></li>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungen-6"><i class="fa fa-check"></i>Übungen</a>
<ul>
<li class="chapter" data-level="" data-path="chap8.html"><a href="chap8.html#aufgabe-1-5"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="chap8.html"><a href="chap8.html#aufgabe-2-5"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="chap8.html"><a href="chap8.html#aufgabe-3-5"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="chap8.html"><a href="chap8.html#aufgabe-4-5"><i class="fa fa-check"></i>Aufgabe 4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="02-firststeps.html"><a href="#weitere-%C3%BCbungen"><i class="fa fa-check"></i><b>9</b> Weitere Übungen</a>
<ul>
<li class="chapter" data-level="9.1" data-path="02-firststeps.html"><a href="#%C3%BCbungen---tidy-data-relational-data-iteration"><i class="fa fa-check"></i><b>9.1</b> Übungen - Tidy data, Relational data, Iteration</a>
<ul>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-2-6"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-3-6"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-4-6"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-5-5"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-6-5"><i class="fa fa-check"></i>Aufgabe 6</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-7-4"><i class="fa fa-check"></i>Aufgabe 7</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-8-4"><i class="fa fa-check"></i>Aufgabe 8</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-9-3"><i class="fa fa-check"></i>Aufgabe 9</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-10-3"><i class="fa fa-check"></i>Aufgabe 10</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-11-2"><i class="fa fa-check"></i>Aufgabe 11</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="02-firststeps.html"><a href="#%C3%BCbungen---objektorientierte-programmierung-in-r-laufzeitverhalten-three-dots-ellipsis"><i class="fa fa-check"></i><b>9.2</b> Übungen - Objektorientierte Programmierung in R, Laufzeitverhalten, three dots ellipsis</a>
<ul>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-1-7"><i class="fa fa-check"></i>Aufgabe 1</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-2-7"><i class="fa fa-check"></i>Aufgabe 2</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-3-7"><i class="fa fa-check"></i>Aufgabe 3</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-4-7"><i class="fa fa-check"></i>Aufgabe 4</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-5-6"><i class="fa fa-check"></i>Aufgabe 5</a></li>
<li class="chapter" data-level="" data-path="weitere-übungen.html"><a href="weitere-übungen.html#aufgabe-6-6"><i class="fa fa-check"></i>Aufgabe 6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html"><i class="fa fa-check"></i><b>10</b> Spezielle Themen und Fallstudien</a>
<ul>
<li class="chapter" data-level="10.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-1-boxplots-und-mnist-daten"><i class="fa fa-check"></i><b>10.1</b> Fallstudie 1: Boxplots und MNIST-Daten</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#boxplots"><i class="fa fa-check"></i><b>10.1.1</b> Boxplots</a></li>
<li class="chapter" data-level="10.1.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#mnist-bilddaten"><i class="fa fa-check"></i><b>10.1.2</b> MNIST-Bilddaten</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-2.1-imdb-internet-movie-database"><i class="fa fa-check"></i><b>10.2</b> Fallstudie 2.1: IMDb Internet Movie Database</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#imdb_bewertungen"><i class="fa fa-check"></i><b>10.2.1</b> <code>imdb_Bewertungen</code></a></li>
<li class="chapter" data-level="10.2.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#wortindex"><i class="fa fa-check"></i><b>10.2.2</b> <code>wortIndex</code></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-2.2-zeichenketten"><i class="fa fa-check"></i><b>10.3</b> Fallstudie 2.2: Zeichenketten</a></li>
<li class="chapter" data-level="10.4" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-3-visualisierung-mit-ggplot2-ggplot2"><i class="fa fa-check"></i><b>10.4</b> Fallstudie 3: Visualisierung mit <code>ggplot2</code> <span class="citation">(Wickham 2016)</span></a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#wahrscheinlichkeitsverteilungen-in-r"><i class="fa fa-check"></i><b>10.4.1</b> Wahrscheinlichkeitsverteilungen in R</a></li>
<li class="chapter" data-level="10.4.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#funktionsplot"><i class="fa fa-check"></i><b>10.4.2</b> Funktionsplot</a></li>
<li class="chapter" data-level="10.4.3" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#histogramme"><i class="fa fa-check"></i><b>10.4.3</b> Histogramme</a></li>
<li class="chapter" data-level="10.4.4" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#zentraler-grenzwertsatz"><i class="fa fa-check"></i><b>10.4.4</b> Zentraler Grenzwertsatz</a></li>
<li class="chapter" data-level="10.4.5" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#quantilplot"><i class="fa fa-check"></i><b>10.4.5</b> Quantilplot</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-4.1-datenimport"><i class="fa fa-check"></i><b>10.5</b> Fallstudie 4.1: Datenimport</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-1-8"><i class="fa fa-check"></i><b>10.5.1</b> Aufgabe 1</a></li>
<li class="chapter" data-level="10.5.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-2---zu-kontrollzwecken-erzeugung-der-daten"><i class="fa fa-check"></i><b>10.5.2</b> Aufgabe 2 - Zu Kontrollzwecken: Erzeugung der Daten</a></li>
<li class="chapter" data-level="10.5.3" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-3---importieren"><i class="fa fa-check"></i><b>10.5.3</b> Aufgabe 3 - Importieren</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-4.2-datenimport--manipulation-und--speicherung"><i class="fa fa-check"></i><b>10.6</b> Fallstudie 4.2: Datenimport, -manipulation und -speicherung</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-1-9"><i class="fa fa-check"></i><b>10.6.1</b> Aufgabe 1</a></li>
<li class="chapter" data-level="10.6.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-2-8"><i class="fa fa-check"></i><b>10.6.2</b> Aufgabe 2</a></li>
<li class="chapter" data-level="10.6.3" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#aufgabe-3-8"><i class="fa fa-check"></i><b>10.6.3</b> Aufgabe 3</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-5-shapiro-wilk-test-und-kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>10.7</b> Fallstudie 5: Shapiro-Wilk-Test und Kolmogorov-Smirnov-Test</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#shapiro-wilk-test"><i class="fa fa-check"></i><b>10.7.1</b> Shapiro-Wilk-Test</a></li>
<li class="chapter" data-level="10.7.2" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#funktionen-zur-mehrfachen-wiederholung-des-shapiro-wilk-tests"><i class="fa fa-check"></i><b>10.7.2</b> Funktionen zur mehrfachen Wiederholung des Shapiro-Wilk-Tests</a></li>
<li class="chapter" data-level="10.7.3" data-path="02-firststeps.html"><a href="#testg%C3%BCte-des-shapiro-wilk-tests-bei-gleichverteilung"><i class="fa fa-check"></i><b>10.7.3</b> Testgüte des Shapiro-Wilk-Tests bei Gleichverteilung</a></li>
<li class="chapter" data-level="10.7.4" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#vergleich-mit-dem-kolmogorov-smirnov-test"><i class="fa fa-check"></i><b>10.7.4</b> Vergleich mit dem Kolmogorov-Smirnov-Test</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#fallstudie-6-datenanalyse"><i class="fa fa-check"></i><b>10.8</b> Fallstudie 6: Datenanalyse</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="spezielle-themen-und-fallstudien.html"><a href="spezielle-themen-und-fallstudien.html#datenanalyse-der-x--y--und-z-werte"><i class="fa fa-check"></i><b>10.8.1</b> Datenanalyse der <code>x</code>-, <code>y</code>- und <code>z</code>-Werte</a></li>
<li class="chapter" data-level="10.8.2" data-path="02-firststeps.html"><a href="#allgemeiner-%C3%BCberblick"><i class="fa fa-check"></i><b>10.8.2</b> Allgemeiner Überblick</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path=""><a href="#pr%C3%BCfungsleistungen"><i class="fa fa-check"></i>Prüfungsleistungen</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#%C3%BCbungsbl%C3%A4tter"><i class="fa fa-check"></i>Übungsblätter</a></li>
<li class="chapter" data-level="" data-path="prüfungsleistungen.html"><a href="prüfungsleistungen.html"><i class="fa fa-check"></i>Implementierungsaufgabe</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="literatur.html"><a href="literatur.html"><i class="fa fa-check"></i>Literatur</a></li>
<li class="chapter" data-level="" data-path="submissions.html"><a href="submissions.html"><i class="fa fa-check"></i>Submissions</a></li>
<li class="part"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="" data-path="system-info.html"><a href="system-info.html"><i class="fa fa-check"></i>System Info</a></li>
<li class="divider"></li>
<li><a href="http://www.bchwtz.de" target="blank"><center>www.<b>BCHWTZ</b>.de</center></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Programming</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ersteschritte" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Erste Schritte<a href="ersteschritte.html#ersteschritte" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Es gibt mehrere Möglichkeiten, R zu starten. Eine interaktive R-Sitzung kann zum Beispiel direkt in einem Terminalfenster (unter Windows auch Eingabefenster genannt) durch die Eingabe des Kommandos „R“ gestartet werden. Statt eine interaktive R-Sitzung zu beginnen, können auch sogenannte R-Skripte in einem Terminalfenster ausgeführt werden.</p>
<p>Im Verlauf dieser Veranstaltung werden wir fast ausschließlich R indirekt über <em>RStudio</em> (genauer <em>RStudio Desktop</em>) starten, was viele Vorteile bietet. <em>RStudio</em> (genauer <em>RStudio Desktop</em>) ist eine integrierte Entwicklungsumgebung (IDE), die das Arbeiten mit R stark vereinfacht, und wie R als Open Source Lizenz zur Verfügung steht.</p>
<p>Ein typisches Fenster in <em>RStudio</em> umfasst mehrere Bereiche. In Abbildung <a href="ersteschritte.html#fig:RStudio-Desktop-1">2.1</a> sehen Sie z. B. drei Bereiche: „Konsole“, „Umgebung“ und „Hilfe“. Im dort abgebildeten Konsolen-Bereich sehen wir zum Beispiel, welche R-Version und Plattform benutzt wird.</p>
<p>Jeder Bereich wiederum kann durch Aktivierung unterschiedlicher Reiter verändert werden. Das gesamte Layout der Bereiche kann individuell angepasst werden (siehe Menüeintrag „View“ / „Panes“). Es passt sich auch dynamisch an: So wird zum Beispiel bei einer Datenvisualisierung statt des „Hilfe“-Bereichs der „Plot“-Bereich aktiviert. Wird ein Skript geladen, erscheint zusätzlich ein Bereich „Editor“. Wir werden später sehen, was R-Skripte (kurz: <em>Skripte</em>) sind und welche Bedeutung sie haben. Wir starten jedoch zuerst mit ganz einfachen Befehlen in der Konsole.</p>
<div class="figure"><span style="display:block;" id="fig:RStudio-Desktop-1"></span>
<img src="gfx/abb1.png" alt="RStudio Bereiche." width="100%" />
<p class="caption">
Figure 2.1: RStudio Bereiche.
</p>
</div>
<p>Im Bereich „Hilfe“ in Abbildung <a href="ersteschritte.html#fig:RStudio-Desktop-1">2.1</a> sehen Sie den Manual-Eintrag zum Befehl <code>.libPaths()</code>. Sie erhalten diesen Eintrag, indem Sie <code>?.libPaths()</code> im Konsolenbereich hinter dem Prompt-Zeichen <code>'&gt;'</code> eingeben. Wir werden später auf das Hilfesystem etwas ausführlicher eingehen.</p>
<div id="numerische-ausdrücke" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Numerische Ausdrücke<a href="#numerische-ausdr%C3%BCcke" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Befehle (engl.: commands) können direkt im Bereich „Konsole“ hinter dem Prompt-Zeichen <code>&gt;</code> eingegeben werden.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="ersteschritte.html#cb3-1" tabindex="-1"></a><span class="dv">6</span><span class="sc">*</span><span class="dv">7</span></span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<p>Sie erhalten sofort das Ergebnis des eingegebenen Ausdrucks. Ist der eingegebene Ausdruck syntaktisch noch nicht abgeschlossen, dann wechselt in der Konsole das Prompt-Zeichen <code>'&gt;'</code> zu <code>'+'</code>; mit einem Semikolon kann ein Abschluss erzwungen werden wie z.B.:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="ersteschritte.html#cb5-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span>; x <span class="sc">+</span> <span class="dv">4</span>; x<span class="sc">*</span> <span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="ersteschritte.html#cb8-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span><span class="dv">10</span>   <span class="co"># Potenzrechnung: 2 hoch 10</span></span></code></pre></div>
<pre><code>## [1] 1024</code></pre>
<p>Wie wir in diesem Beispiel zusätzlich sehen können, werden wie in vielen anderen Programmiersprachen auch alle Zeichen in einer Zeile, die nach einem <code>'#'</code> folgen, als Kommentar interpretiert.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="ersteschritte.html#cb10-1" tabindex="-1"></a><span class="dv">10</span><span class="sc">/</span><span class="dv">3</span>   <span class="co"># Division</span></span></code></pre></div>
<pre><code>## [1] 3.333333</code></pre>
<p>Auch sehen wir in diesem Beispiel, dass R wie C, C++ oder Java nicht ein Komma, sondern einen Punkt als Dezimaltrennzeichen verwendet.</p>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Alle Zeichen in einer Zeile, die nach einem <code>#</code> folgen, werden als Kommentar interpretiert.</li>
<li>Punkt ist Dezimaltrennzeichen</li>
</ul>
</blockquote>
</div>
<div id="variablen" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Variablen<a href="ersteschritte.html#variablen" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Wir können das Ergebnis einer Berechnung natürlich auch einer Variablen zuweisen. Wie wir später sehen werden, handelt es sich dabei um eine <strong>globale</strong> Variable!</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="ersteschritte.html#cb12-1" tabindex="-1"></a>res <span class="ot">=</span> <span class="dv">10</span><span class="sc">/</span><span class="dv">3</span>       <span class="co"># &#39;=&#39; sollte vermieden werden</span></span></code></pre></div>
<p>Allerdings bleibt dann das Ergebnis der Berechnung verborgen. Dies sehen wir erst, wenn wir <code>print(res)</code> oder kürzer <code>res</code> eingeben</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="ersteschritte.html#cb13-1" tabindex="-1"></a>res</span></code></pre></div>
<pre><code>## [1] 3.333333</code></pre>
<p>Es ist allerdings in R üblich, anstelle von <code>'='</code> den Operator <code>'&lt;-'</code>, der aus zwei Buchstaben besteht, für eine Zuweisung zu benutzen. Das hat zum Teil historische Gründe; aber es gibt auch spezielle Situationen, wo <code>'='</code> als Zuweisungsoperator nicht wie erwartet funktioniert. Also besser:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="ersteschritte.html#cb15-1" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">/</span><span class="dv">3</span>      <span class="co"># Besser</span></span>
<span id="cb15-2"><a href="ersteschritte.html#cb15-2" tabindex="-1"></a>res</span></code></pre></div>
<pre><code>## [1] 3.333333</code></pre>
<p>Weil Zuweisungen oft benutzt werden, gibt es für <code>'&lt;-'</code> in RStudio eine besondere Tastenkombination: <code>Alt-'-'</code>. Im Gegensatz zu C oder C++ müssen in R Variablen nicht vorher vereinbart werden und sind nicht fest für den Rest ihrer Geltungsdauer an einem bestimmten Datentyp gebunden, wie das nächste Beispiel zeigt:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="ersteschritte.html#cb17-1" tabindex="-1"></a>name <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb17-2"><a href="ersteschritte.html#cb17-2" tabindex="-1"></a>name</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="ersteschritte.html#cb19-1" tabindex="-1"></a>name <span class="ot">&lt;-</span> <span class="st">&quot;zehn&quot;</span></span>
<span id="cb19-2"><a href="ersteschritte.html#cb19-2" tabindex="-1"></a>name</span></code></pre></div>
<pre><code>## [1] &quot;zehn&quot;</code></pre>
<p>Zuerst verweist in dem obigen Beispiel die Variable <code>name</code> auf den numerischen Wert 10. Nach einer erneuten Zuweisung weist dann die Variable <code>name</code> auf die Zeichenkette “zehn”, also auf ein Objekt eines ganz anderen Datentyps. Dies ist in C oder C++ so nicht möglich! Wie wir sehen werden, ist R vektorbasiert und unsere vorläufige Analyse, dass in dem obigen Beispiel <code>name</code> auf den numerischen Wert 10 bzw. auf eine Zeichenkette verweist, ist ungenau. Besser wäre die Formulierung, dass im ersten Fall die Variable <code>name</code> (in Verbindung mit der entsprechenden Umgebung (Environment)) auf einen numerischen Vektor zeigt, der aus nur einem Element besteht. Für den zweiten Fall gilt Ähnliches.</p>
<p>R unterscheidet grundsätzlich zwischen Groß- und Kleinschreibung. So bezeichnen zum Beispiel <code>res</code> und <code>Res</code> zwei unterschiedliche Variablen:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="ersteschritte.html#cb21-1" tabindex="-1"></a>Res <span class="ot">&lt;-</span> <span class="fl">1.4</span>   <span class="co"># Groß- und Kleinschreibung beachten!</span></span>
<span id="cb21-2"><a href="ersteschritte.html#cb21-2" tabindex="-1"></a>Res</span></code></pre></div>
<pre><code>## [1] 1.4</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="ersteschritte.html#cb23-1" tabindex="-1"></a>res</span></code></pre></div>
<pre><code>## [1] 3.333333</code></pre>
<p>Es gibt Einschränkungen für Variablennamen, auf die wir aber nicht detailliert eingehen werden. Abgesehen von Schlüsselworten wie <code>TRUE</code> oder <code>if</code> (siehe auch <code>?Reserved</code> für eine Liste aller Schlüsselworte) sind grundsätzlich alphanumerische Zeichen aus dem ursprünglichen ASCII-Zeichensatz erlaubt, aber keine Umlaute oder Sonderzeichen mit Ausnahme von <code>'_'</code> und <code>'.'</code> (In C und C++ hingegen ist das Zeichen <code>'.'</code> Bestandteil der sogenannten Punktnotation (genutzt in Strukturen und Klassen) und darf nicht in einem Variablennamen vorkommen.). Das erste Zeichen sollte ein Buchstabe sein. Der Begriff <code>syntatic names</code> bezieht sich auf erlaubte Namen (im Gegensatz zu <code>non-syntatic names</code>).</p>
<p>Mittlerweile gibt es eine ganze Reihe von unterschiedlichen Style-Guides, wie:</p>
<ul>
<li><a href="https://jef.works/R-style-guide/" class="uri">https://jef.works/R-style-guide/</a></li>
<li><a href="https://google.github.io/styleguide/Rguide.xml" class="uri">https://google.github.io/styleguide/Rguide.xml</a></li>
<li><a href="http://adv-r.had.co.nz/Style.html" class="uri">http://adv-r.had.co.nz/Style.html</a></li>
</ul>
<p>Wir wollen im Folgenden der Empfehlung folgen, Variablen- und Funktionsnamen klein zu schreiben und Großbuchstaben lediglich für die Trennung separater Worte zu nutzen (der sogenannte „<em>camelCase</em>“, im Gegensatz zu dem von manchen Autoren bevorzugten „<em>snake_case</em>“). Insbesondere wollen wir auch nicht das Sonderzeichen <code>'.'</code> in Variablen- und Funktionsnamen nutzen, da es in manchen Bereichen wie Klassen eine unterschiedliche Bedeutung hat.</p>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Für eine Zuweisung <code>&lt;-</code> benutzen.</li>
<li>Die Tastenkombination <code>Alt + '-'</code> steht in RStudio für <code>&lt;-</code>.</li>
<li>In R werden Anweisungen nicht durch ein Semikolon abgeschlossen.</li>
<li>Variablen müssen nicht vorher vereinbart werden.</li>
<li>Variablen sind nicht fest an einen bestimmten Datentyp gebunden.</li>
<li>R unterscheidet zwischen Groß- und Kleinschreibung.</li>
</ul>
</blockquote>
</div>
<div id="vektoren" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Vektoren<a href="ersteschritte.html#vektoren" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vektoren spielen in R eine zentrale Rolle und wir werden in einem späteren Kapitel detailliert auf Vektoren eingehen. An dieser Stelle wollen wir zur Einführung lediglich ein erstes Beispiel mit numerischen Vektoren vorstellen. Ein Vektor ist wie ein Feld (array) eine Datenstruktur, die eine Folge von Elementen desselben Typs enthält. Erzeugt werden soll im nächsten Beispiel ein einfacher Datensatz <code>p</code>, der die ersten zehn Primzahlen enthält:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="ersteschritte.html#cb25-1" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">11</span>,<span class="dv">13</span>,<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">23</span>,<span class="dv">29</span>) <span class="co"># Erzeugt einen Vektor der Länge 10</span></span>
<span id="cb25-2"><a href="ersteschritte.html#cb25-2" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>##  [1]  2  3  5  7 11 13 17 19 23 29</code></pre>
<p><code>p</code> verweist nun auf einen Vektor, der die ersten zehn Primzahlen enthält. Die Größen <code>2, 3, 5, 7, 11, 13, 17, 19, 23, 29</code> werden mithilfe der Funktion <code>c()</code> zu einem numerischen Vektor zusammengefasst und der Variablen <code>p</code> zugewiesen; <code>c</code> steht hier für <em>concatenate</em> (deutsch: aneinanderhängen) und gibt immer einen Vektor zurück. Wie in C haben wir mithilfe des Indexoperators <code>[]</code> wahlfreien Zugriff auf die einzelnen Elemente des Vektors. Aber im Gegensatz zu C und vielen anderen Programmiersprachen beginnt die Indexierung in R nicht bei 0 sondern bei 1!</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="ersteschritte.html#cb27-1" tabindex="-1"></a>p[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="ersteschritte.html#cb29-1" tabindex="-1"></a>p[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="ersteschritte.html#cb31-1" tabindex="-1"></a>p[<span class="dv">10</span>]</span></code></pre></div>
<pre><code>## [1] 29</code></pre>
<p>Was passiert, wenn wir über die Indexgrenzen hinweggehen? In C und C++ ist dies ein Fehler!</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="ersteschritte.html#cb33-1" tabindex="-1"></a>p[<span class="dv">11</span>]</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="ersteschritte.html#cb35-1" tabindex="-1"></a>p[<span class="dv">12</span>]</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="ersteschritte.html#cb37-1" tabindex="-1"></a>p[<span class="dv">13</span>]</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>In R hingegen ist dies nicht fehlerhaft! R benutzt das Symbol <code>NA</code> (<em>not available</em>), um anzuzeigen, dass ein Wert nicht vorhanden ist (im Englischen oft als „missing data“ bezeichnet). Unser Beispieldatensatz besteht nach wie vor aus 10 Elementen. Was passiert aber, wenn wir dem 13. Element einen Wert zuweisen?</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="ersteschritte.html#cb39-1" tabindex="-1"></a>p[<span class="dv">13</span>] <span class="ot">&lt;-</span> <span class="dv">41</span></span>
<span id="cb39-2"><a href="ersteschritte.html#cb39-2" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>##  [1]  2  3  5  7 11 13 17 19 23 29 NA NA 41</code></pre>
<p>Offenbar hat sich jetzt die Größe des Vektors <code>p</code> dynamisch angepasst: <code>p</code> besteht nun aus dreizehn Elementen. Sowohl das elfte als auch das zwölfte Element hat jedoch keinen regulären numerischen Wert. Auf Vektoren werden wir später noch sehr ausführlich eingehen.</p>
<p>In R kann man ähnlich wie z.B. in MATLAB Operatoren direkt auf Vektoren anwenden:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="ersteschritte.html#cb41-1" tabindex="-1"></a>p</span></code></pre></div>
<pre><code>##  [1]  2  3  5  7 11 13 17 19 23 29 NA NA 41</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="ersteschritte.html#cb43-1" tabindex="-1"></a>p<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1]    4    9   25   49  121  169  289  361  529  841   NA   NA 1681</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="ersteschritte.html#cb45-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>p <span class="sc">+</span> <span class="dv">1</span></span></code></pre></div>
<pre><code>##  [1]  5  7 11 15 23 27 35 39 47 59 NA NA 83</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="ersteschritte.html#cb47-1" tabindex="-1"></a>p <span class="sc">%%</span> <span class="dv">4</span> <span class="co"># Modulo-Operator</span></span></code></pre></div>
<pre><code>##  [1]  2  3  1  3  3  1  1  3  3  1 NA NA  1</code></pre>
<p>Hier bezeichnet „<code>%%</code>“ den Modulo-Operator; er gibt den Rest bei einer ganzzahligen Division zurück. Ebenso können Funktionen auf Vektoren angewandt werden. So gibt es zum Beispiel die Funktionen <code>mean()</code> und <code>sd()</code>, die das arithmetische Mittel und die Standardabweichung zurückgeben.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="ersteschritte.html#cb49-1" tabindex="-1"></a><span class="fu">mean</span>(p)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="ersteschritte.html#cb51-1" tabindex="-1"></a><span class="fu">sd</span>(p)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Hier bereiten die fehlenden Werte Probleme und die beiden Funktionen können die statistischen Größen nicht berechnen. Allerdings kann man bei vielen Funktionen durch den Parameter <code>na.rm = TRUE</code> angeben, dass fehlende Werte nicht berücksichtigt werden sollen:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="ersteschritte.html#cb53-1" tabindex="-1"></a><span class="fu">mean</span>(p, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 15.45455</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="ersteschritte.html#cb55-1" tabindex="-1"></a><span class="fu">sd</span>(p, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 12.04461</code></pre>
<p>Es ist nicht überraschend, dass man Funktionen wie <code>mean()</code> oder <code>sd()</code> auf Vektoren anwenden kann. Aber wie sieht dies mit Funktionen wie <code>sqrt()</code> aus? Die Funktion <code>sqrt()</code> gibt die Wurzel einer Zahl zurück und wird in vielen Programmiersprachen üblicherweise auf skalare Werte angewandt.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="ersteschritte.html#cb57-1" tabindex="-1"></a><span class="fu">sqrt</span>(p)</span></code></pre></div>
<pre><code>##  [1] 1.414214 1.732051 2.236068 2.645751 3.316625 3.605551 4.123106 4.358899
##  [9] 4.795832 5.385165       NA       NA 6.403124</code></pre>
<p>Auch hier haben wir ein ähnliches Verhalten wie in MATLAB; die Funktion <code>sqrt()</code> wird auf jedes Element des Vektors angewandt. Als Ergebnis wird ein Vektor gleicher Länge zurückgegeben („<em>vector in, vector out</em>“). Solche Funktionen nennt man auch <em>vektorisierbar</em>. In einem folgenden Abschnitt werden wir sehen, dass zum Beispiel Funktionen, die eine <code>if-else</code> Verzweigung enthalten, nicht (direkt) vektorisierbar sind.</p>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Mit <code>c()</code> können Vektoren erzeugt werden.</li>
<li>Indexierung beginnt in R nicht bei <code>0</code> sondern bei <code>1</code>!</li>
<li><code>NA</code> (not available) wird benutzt, um anzuzeigen, dass ein Wert nicht vorhanden ist.</li>
<li><code>%%</code> Modulo-Operator</li>
<li>Operatoren und Funktionen können direkt auf Vektoren angewandt werden.</li>
<li>Durch <code>na.rm = TRUE</code> werden bei vielen Funktionen <code>NA</code>-Werte ignoriert</li>
<li>Funktionen: <code>mean()</code>, <code>sd()</code>, <code>sqrt()</code></li>
<li>vektorisierbare Funktionen</li>
</ul>
</blockquote>
</div>
<div id="recycling" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Recycling<a href="ersteschritte.html#recycling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Manchmal verlangt eine Operation, dass alle beteiligten Vektoren dieselbe Länge haben. In diesem Fall ergänzt R die kürzeren Vektoren, indem es seine Werte periodisch wiederholt. Dieses Verhalten nennt man auch <em>Recycling</em>.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="ersteschritte.html#cb59-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>) <span class="co"># entspricht c(1,1,1,1,1,1)</span></span>
<span id="cb59-2"><a href="ersteschritte.html#cb59-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 1 1 1 1 1</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="ersteschritte.html#cb61-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</span>
<span id="cb61-2"><a href="ersteschritte.html#cb61-2" tabindex="-1"></a>x<span class="sc">+</span>y</span></code></pre></div>
<pre><code>## [1] 2 3 2 3 2 3</code></pre>
<p>Der Funktionsaufruf <code>rep(x, n)</code> (für <em>replicate</em>) erzeugt ein Objekt des gleichen Typs wie <code>x</code>, das den Wert von <code>x</code> genau <code>n</code>-mal wiederholt. Berechnet wurde in diesem Fall also</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="ersteschritte.html#cb63-1" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 2 3 2 3 2 3</code></pre>
<p>Allerdings gibt es eine Warnung, wenn die Länge des größeren Vektors kein Vielfaches des kleineren Vektors ist:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="ersteschritte.html#cb65-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">6</span>)</span>
<span id="cb65-2"><a href="ersteschritte.html#cb65-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>   <span class="co"># wie c(1L, 2L, 3L, 4L)</span></span>
<span id="cb65-3"><a href="ersteschritte.html#cb65-3" tabindex="-1"></a><span class="fu">str</span>(y)</span></code></pre></div>
<pre><code>##  int [1:4] 1 2 3 4</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="ersteschritte.html#cb67-1" tabindex="-1"></a>x<span class="sc">+</span>y</span></code></pre></div>
<pre><code>## Warning in x + y: longer object length is not a multiple of shorter object
## length</code></pre>
<pre><code>## [1] 2 3 4 5 2 3</code></pre>
<p>Allgemein wird durch einen Ausdruck wie <code>n:m</code> (wobei <code>n</code> und <code>m</code> ganze Zahlen sind) ein Vektor erzeugt, dessen erstes Element <code>n</code> und dessen letztes Element <code>m</code> ist und aufeinanderfolgende Elemente sich entweder alle um 1 oder alle um -1 unterscheiden.</p>
<p>Wie man in der Manual-Hilfe sieht, ist <code>rep_len(x, length.out)</code> eine Variante von <code>rep()</code>. <code>rep_len(x, length.out)</code> gibt eine periodisch fortgesetzte Kopie von <code>x</code> mit der Länge <code>length.out</code> zurück:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="ersteschritte.html#cb70-1" tabindex="-1"></a><span class="fu">rep_len</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 1 2 3 1 2</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="ersteschritte.html#cb72-1" tabindex="-1"></a><span class="fu">rep_len</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">7</span>)</span></code></pre></div>
<pre><code>## [1] 1 2 3 1 2 3 1</code></pre>
<p><strong>Fragen</strong></p>
<ul>
<li>Welchen Wert hat der Vektor <code>7.1:3.3</code>?</li>
<li>Welchen Wert hat der Vektor <code>2:5 + 10</code>?</li>
</ul>
<p>Wenn man weiß, ob der Additions- oder der Bereichsoperator eine höhere Priorität hat, dann kann man die letzte Frage leicht beantworten. <code>?Syntax</code> liefert dabei folgende Antwort; die Operatoren sind gemäß ihrer Priorität (mit höchster Priorität zuerst) aufgelistet:</p>
<table>
<thead>
<tr class="header">
<th>Operator</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>::</code> <code>:::</code></td>
<td>access variables in a namespace</td>
</tr>
<tr class="even">
<td><code>$</code> <code>@</code></td>
<td>component / slot extraction</td>
</tr>
<tr class="odd">
<td><code>[</code> <code>[[</code></td>
<td>indexing</td>
</tr>
<tr class="even">
<td><code>^</code></td>
<td>exponentiation (right to left)</td>
</tr>
<tr class="odd">
<td><code>-</code> <code>+</code></td>
<td>unary minus and plus</td>
</tr>
<tr class="even">
<td><code>:</code></td>
<td>sequence operator</td>
</tr>
<tr class="odd">
<td><code>%any%</code></td>
<td>special operators (including %% and %/%)</td>
</tr>
<tr class="even">
<td><code>*</code> <code>/</code></td>
<td>multiply, divide</td>
</tr>
<tr class="odd">
<td><code>+</code> <code>-</code></td>
<td>(binary) add, subtract</td>
</tr>
<tr class="even">
<td><code>&lt;</code> <code>&gt;</code> <code>&lt;=</code> <code>&gt;=</code> <code>==</code> <code>!=</code></td>
<td>ordering and comparison</td>
</tr>
<tr class="odd">
<td><code>!</code></td>
<td>negation</td>
</tr>
<tr class="even">
<td><code>&amp;</code> <code>&amp;&amp;</code></td>
<td>and</td>
</tr>
<tr class="odd">
<td><code>|</code> <code>||</code></td>
<td>or</td>
</tr>
<tr class="even">
<td><code>~</code></td>
<td>as in formulae</td>
</tr>
<tr class="odd">
<td><code>-&gt;</code> <code>-&gt;&gt;</code></td>
<td>rightwards assignment</td>
</tr>
<tr class="even">
<td><code>&lt;-</code> <code>&lt;&lt;-</code></td>
<td>assignment (right to left)</td>
</tr>
<tr class="odd">
<td><code>=</code></td>
<td>assignment (right to left)</td>
</tr>
<tr class="even">
<td><code>?</code></td>
<td>help (unary and binary)</td>
</tr>
</tbody>
</table>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Recycling</li>
<li>Funktionen: <code>rep()</code></li>
<li><code>y &lt;- 1:4</code> (oder allgemeiner <code>n:m</code>)</li>
<li>Priorität der Operatoren</li>
</ul>
</blockquote>
</div>
<div id="rstudio" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> RStudio<a href="ersteschritte.html#rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Im Bereich „Umgebung“ sehen wir nun die von uns erzeugten globalen Variablen und deren aktuelle Werte. Hier werden die Namen aller erzeugten Objekte aufgelistet; dies bezieht sich sowohl auf Daten als auch auf Funktionen (und andere Objekte). Zusätzlich erhält man neben den Namen eine kurze und kompakte Zusammenfassung der entsprechenden Werte.</p>
<p>Mithilfe der Cursortasten ↑ und ↓ kann im Konsolenbereich von RStudio innerhalb der bereits eingegebenen Befehle navigiert werden. Mit den → und ← kann der Cursor innerhalb der aktuellen Befehlszeile bewegt werden und gegebenenfalls Korrekturen vorgenommen werden. Alternativ kann der Reiter „History“ (in dem Bereich rechts oben) aktiviert werden, so dass alle eingegebenen Befehle sichtbar werden.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-26"></span>
<img src="gfx/abb2.png" alt="Die erzeugten globalen Variablen in RStudio im Bereich 'Umgebung' (Environment)." width="100%" />
<p class="caption">
Figure 2.2: Die erzeugten globalen Variablen in RStudio im Bereich ‘Umgebung’ (Environment).
</p>
</div>
<p>RStudio bietet viele hilfreiche Unterstützungen an, von denen wir allerdings nur einige vorstellen werden. Weiterführende Dokumentationen finden Sie u.a. unter dem Menüeintrag „Help“ / „RStudio Docs“.
RStudio bietet ein umfangreiches Hilfesystem an. Wir wollen dies an einem Beispiel demonstrieren.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="ersteschritte.html#cb74-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4</span><span class="sc">*</span>pi, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb74-2"><a href="ersteschritte.html#cb74-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##   [1]  0.0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0  1.1  1.2  1.3  1.4
##  [16]  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
##  [31]  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.0  4.1  4.2  4.3  4.4
##  [46]  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9
##  [61]  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.0  7.1  7.2  7.3  7.4
##  [76]  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9
##  [91]  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9 10.0 10.1 10.2 10.3 10.4
## [106] 10.5 10.6 10.7 10.8 10.9 11.0 11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9
## [121] 12.0 12.1 12.2 12.3 12.4 12.5</code></pre>
<p>Aus diesem Beispiel kann man bereits erahnen, was die Funktion <code>seq()</code> bewirkt. Durch <code>help(seq)</code> oder kürzer durch <code>?seq</code> erhält man in RStudio den entsprechenden Manual-Eintrag (siehe Abbildung <a href="ersteschritte.html#fig:manual-eintrag-seq">2.3</a>). Weiterhin bezeichnet hier <code>pi</code> eine in R eingebaute Konstante, die der Kreiszahl entspricht (Verhältnis des Umfangs eines Kreises zu seinem Durchmesser).</p>
<div class="figure"><span style="display:block;" id="fig:manual-eintrag-seq"></span>
<img src="gfx/abb3.png" alt="Manual-Eintrag der Funktion seq() angezeigt in RStudio." width="100%" />
<p class="caption">
Figure 2.3: Manual-Eintrag der Funktion <code>seq()</code> angezeigt in RStudio.
</p>
</div>

<p>Die Eingabe von <code>x</code> im Konsolenbereich (hinter dem Prompt-Zeichen <code>&gt;</code>) bewirkt, dass die Funktion <code>print(x)</code> aufgerufen wird. Enthält <code>x</code> viele Daten, kann dies schnell sehr unübersichtlich werden. Daher gibt es die Funktion <code>str()</code>, die eine alternative kompakte Darstellung bereitstellt (<code>str</code> steht hier für <em>structure</em>):</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="ersteschritte.html#cb76-1" tabindex="-1"></a><span class="fu">str</span>(x)</span></code></pre></div>
<pre><code>##  num [1:126] 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 ...</code></pre>
<p>Hieraus entnehmen wir, dass <code>x</code> ein numerischer Vektor mit insgesamt 126 Elementen ist.
Schließlich wollen wir noch den „Plot“-Bereich in RStudio kurz vorstellen. Dazu geben wir folgenden Befehl ein.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="ersteschritte.html#cb78-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> x, <span class="at">y =</span> <span class="fu">sin</span>(x), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p>Durch <code>type = "l"</code> legen wir fest, dass die einzelnen Punkte durch Linien verbunden werden sollen, und durch <code>col = "blue"</code>, dass die Zeichenfarbe blau sein soll wie dies aus Abbildung <a href="ersteschritte.html#fig:first-plot-R">2.4</a> hervorgeht..</p>
<div class="figure"><span style="display:block;" id="fig:first-plot-R"></span>
<img src="gfx/abb4.png" alt="Plot in RStudio." width="100%" />
<p class="caption">
Figure 2.4: Plot in RStudio.
</p>
</div>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Cursortasten im Konsolenbereich von RStudio</li>
<li>Durch <code>?xyz</code> erhält man den Manual-Eintrag von <code>xyz</code></li>
<li><code>str()</code> für eine kompakte textuelle Darstellung</li>
</ul>
</blockquote>
</div>
<div id="demos" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Demos<a href="ersteschritte.html#demos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>R bietet standardmäßig unterschiedliche Präsentationen an (siehe <code>?demo</code>). Um z.B. eine kurze Demo über die Grafikmöglichkeiten in R zu erhalten, geben sie <code>demo(graphic)</code> ein.</p>
<p>Daneben gibt es hauptsächlich zu Übungszwecken unterschiedliche Datensätze; siehe <code>?datasets</code> bzw. <code>library(help = "datasets")</code> <span class="citation">(<a href="#ref-datasets">R Core Team 2021</a>)</span>. Wir werden kurz auf den Datensatz <code>Nile</code> eingehen, der die jährliche Durchflussmenge <span class="math inline">\(\left(\text{in }\left[10^8 m^3\right]\right)\)</span> am Nil in Aswan (früher Assuan) zwischen 1871 und 1970 beschreibt.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="ersteschritte.html#cb79-1" tabindex="-1"></a>Nile</span></code></pre></div>
<pre><code>## Time Series:
## Start = 1871 
## End = 1970 
## Frequency = 1 
##   [1] 1120 1160  963 1210 1160 1160  813 1230 1370 1140  995  935 1110  994 1020
##  [16]  960 1180  799  958 1140 1100 1210 1150 1250 1260 1220 1030 1100  774  840
##  [31]  874  694  940  833  701  916  692 1020 1050  969  831  726  456  824  702
##  [46] 1120 1100  832  764  821  768  845  864  862  698  845  744  796 1040  759
##  [61]  781  865  845  944  984  897  822 1010  771  676  649  846  812  742  801
##  [76] 1040  860  874  848  890  744  749  838 1050  918  986  797  923  975  815
##  [91] 1020  906  901 1170  912  746  919  718  714  740</code></pre>
<p>Oder in kompakter Darstellung:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="ersteschritte.html#cb81-1" tabindex="-1"></a><span class="fu">str</span>(Nile)</span></code></pre></div>
<pre><code>##  Time-Series [1:100] from 1871 to 1970: 1120 1160 963 1210 1160 1160 813 1230 1370 1140 ...</code></pre>
<p>Hierbei werden wir jedoch nicht auf alle Einzelheiten eingehen, sondern wir wollen beispielhaft einige Möglichkeiten von R aufzeigen. Mittelwert und Standardabweichung sind schnell berechnet:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="ersteschritte.html#cb83-1" tabindex="-1"></a><span class="fu">mean</span>(Nile)</span></code></pre></div>
<pre><code>## [1] 919.35</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="ersteschritte.html#cb85-1" tabindex="-1"></a><span class="fu">sd</span>(Nile)</span></code></pre></div>
<pre><code>## [1] 169.2275</code></pre>
<p>Mit <code>summary()</code> erhalten wir diese beiden Werte zusammen mit vier anderen wichtigen statistischen Kennzahlen (Minimum, unteres und oberes Quartil und Median), auf die wir an dieser Stelle nicht weiter eingehen wollen (siehe auch <code>?summary</code>):</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="ersteschritte.html#cb87-1" tabindex="-1"></a><span class="fu">summary</span>(Nile)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   456.0   798.5   893.5   919.4  1032.5  1370.0</code></pre>
<p>Ein Plot der Daten ist ebenfalls schnell erzeugt:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="ersteschritte.html#cb89-1" tabindex="-1"></a><span class="fu">plot</span>(Nile)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:plot-Nile"></span>
<img src="bchwtz-rprg_files/figure-html/plot-Nile-1.png" alt="(Zeitreihen-)Diagramm des Nile Datensatzes (R Core Team 2021)." width="672" />
<p class="caption">
Figure 2.5: (Zeitreihen-)Diagramm des <code>Nile</code> Datensatzes <span class="citation">(<a href="#ref-datasets">R Core Team 2021</a>)</span>.
</p>
</div>

<p>Ebenso sind ein Histogramm:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="ersteschritte.html#cb90-1" tabindex="-1"></a><span class="fu">hist</span>(Nile)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist-Nile"></span>
<img src="bchwtz-rprg_files/figure-html/hist-Nile-1.png" alt="Histogramm des Nile Datensatzes (R Core Team 2021)" width="672" />
<p class="caption">
Figure 2.6: Histogramm des <code>Nile</code> Datensatzes <span class="citation">(<a href="#ref-datasets">R Core Team 2021</a>)</span>
</p>
</div>

<p>und ein Boxplot schnell erstellt:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="ersteschritte.html#cb91-1" tabindex="-1"></a><span class="fu">boxplot</span>(Nile)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:boxplot-Nile"></span>
<img src="bchwtz-rprg_files/figure-html/boxplot-Nile-1.png" alt="(ref:boxplot-ts-Nile)" width="672" />
<p class="caption">
Figure 2.7: (ref:boxplot-ts-Nile)
</p>
</div>
<p>In R sind bereits viele Funktionen zu häufig verwendeten Wahrscheinlichkeitsverteilungen implementiert. Exemplarisch wollen wir an dieser Stelle die Funktionen <code>rnorm()</code> und <code>runif()</code> betrachten (siehe <code>?rnorm</code> und <code>?runif</code>). Beide Funktionen geben Pseudozufallszahlen gemäß der Normalverteilung bzw. der Gleichverteilung zurück. Werden keine weiteren Argumente spezifiziert, dann wird bei der Normalverteilung Mittelwert 0 und Standardabweichung 1 angenommen; entsprechend gibt <code>rnorm(n)</code> einen Vektor mit <code>n</code> normalverteilten Pseudozufallszahlen zurück:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="ersteschritte.html#cb92-1" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1]  0.2848986  0.6938826 -1.7975100  0.1847127 -0.1818487  0.3151224
##  [7] -0.2956293  0.8488951  1.0077057  0.7784540</code></pre>
<p>Bei der Gleichverteilung wird standardmäßig vom Intervall [0,1] ausgegangen; entsprechend gibt <code>runiform(n)</code> einen Vektor mit <code>n</code> in [0,1] gleichverteilten Pseudozufallszahlen zurück:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="ersteschritte.html#cb94-1" tabindex="-1"></a><span class="fu">runif</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] 0.2400944 0.2714508 0.9869360 0.7561739 0.4674055 0.7988838 0.8166405
##  [8] 0.1266898 0.7256025 0.1888105</code></pre>
<p>Wenn wir im Folgenden von erzeugten Zufallszahlen (oder zufälligen Werten) sprechen, dann meinen wir stets <em>Pseudozufallszahlen</em>.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="ersteschritte.html#cb96-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>)</span>
<span id="cb96-2"><a href="ersteschritte.html#cb96-2" tabindex="-1"></a><span class="fu">summary</span>(y)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -3.37606 -0.65934 -0.01919  0.02107  0.69615  3.53086</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="ersteschritte.html#cb98-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100000</span>)</span>
<span id="cb98-2"><a href="ersteschritte.html#cb98-2" tabindex="-1"></a><span class="fu">summary</span>(x)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -4.255110 -0.676872 -0.001653  0.000677  0.677082  4.104361</code></pre>
<p>Um zu prüfen, ob die erzeugten Zufallszahlen einer Normalverteilung genügen, können wir als ersten Test ein Histogramm erzeugen:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="ersteschritte.html#cb100-1" tabindex="-1"></a><span class="fu">hist</span>(y)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist-10breaks"></span>
<img src="bchwtz-rprg_files/figure-html/hist-10breaks-1.png" alt="Histogramm von 100.000 normalverteilten Zufallszahlen verteilt auf 100 Klassen." width="672" />
<p class="caption">
Figure 2.8: Histogramm von 100.000 normalverteilten Zufallszahlen verteilt auf 100 Klassen.
</p>
</div>

<p>Die Anzahl der Klassen im Histogramm ist selbst für den kleinen Datensatz <code>y</code> eigentlich zu klein. Es ist oft nicht ganz so einfach, die „richtige“ Anzahl der Klassen in einem Histogramm zu bestimmen. Für den größeren Datensatz <code>x</code> wollen wir 100 unterschiedliche Klassen im Histogramm benutzen. Mit <code>breaks</code> kann die Anzahl der Klassen im Histogramm beeinflusst werden (siehe <code>?hist</code>).</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="ersteschritte.html#cb101-1" tabindex="-1"></a><span class="fu">hist</span>(x, <span class="at">breaks =</span> <span class="dv">100</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist-100breaks"></span>
<img src="bchwtz-rprg_files/figure-html/hist-100breaks-1.png" alt="Histogramm von 100.000 normalverteilten Zufallszahlen verteilt auf 100 Klassen." width="672" />
<p class="caption">
Figure 2.9: Histogramm von 100.000 normalverteilten Zufallszahlen verteilt auf 100 Klassen.
</p>
</div>

<p>Wenn man Abbildung <a href="ersteschritte.html#fig:hist-100breaks">2.9</a> mit der „hochskalierten“ theoretischen Wahrscheinlichkeitsdichte der Normalverteilung in der nächsten Abbildung <a href="ersteschritte.html#fig:theoret-NV">2.10</a> vergleicht, dann sieht man, dass die so erzeugten Zufallszahlen diesen ersten groben Test bestanden haben. Für die Erzeugung der Abbildung <a href="ersteschritte.html#fig:theoret-NV">2.10</a> benutzen wir dabei in der Plot-Funktion die Funktion <code>dnorm()</code>, die die Werte der Wahrscheinlichkeitsdichte (density) der Normalverteilung zurückgibt:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="ersteschritte.html#cb102-1" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb102-2"><a href="ersteschritte.html#cb102-2" tabindex="-1"></a><span class="fu">plot</span>(z, <span class="dv">100000</span><span class="sc">*</span><span class="fu">dnorm</span>(z), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:theoret-NV"></span>
<img src="bchwtz-rprg_files/figure-html/theoret-NV-1.png" alt="Wahrscheinlichkeitsdichte der Normalverteilung \(N(0,1)\) multipliziert mit \(10^5\)." width="672" />
<p class="caption">
Figure 2.10: Wahrscheinlichkeitsdichte der Normalverteilung <span class="math inline">\(N(0,1)\)</span> multipliziert mit <span class="math inline">\(10^5\)</span>.
</p>
</div>

<p>Das Gleiche wollen wir mit zufällig erzeugten gleichverteilten Werten wiederholen:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="ersteschritte.html#cb103-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000</span>)</span>
<span id="cb103-2"><a href="ersteschritte.html#cb103-2" tabindex="-1"></a><span class="fu">summary</span>(y)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## 0.002167 0.245176 0.491357 0.500839 0.752507 0.999600</code></pre>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="ersteschritte.html#cb105-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100000</span>)</span>
<span id="cb105-2"><a href="ersteschritte.html#cb105-2" tabindex="-1"></a><span class="fu">summary</span>(x)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## 0.0000131 0.2514110 0.5023439 0.5010802 0.7507626 0.9999549</code></pre>
<p>Auch wollen wir wieder die Histogramme des kleinen und des großen Datensatzes erzeugen:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="ersteschritte.html#cb107-1" tabindex="-1"></a><span class="fu">hist</span>(y)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist-equ-small"></span>
<img src="bchwtz-rprg_files/figure-html/hist-equ-small-1.png" alt="Histogramm von 1.000 gleichverteilten Zufallszahlen im Intervall [0,1] verteilt auf 10 Klassen." width="672" />
<p class="caption">
Figure 2.11: Histogramm von 1.000 gleichverteilten Zufallszahlen im Intervall [0,1] verteilt auf 10 Klassen.
</p>
</div>

<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="ersteschritte.html#cb108-1" tabindex="-1"></a><span class="fu">hist</span>(x, <span class="at">breaks =</span> <span class="dv">100</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist-equ"></span>
<img src="bchwtz-rprg_files/figure-html/hist-equ-1.png" alt="Histogramm von 100.000 gleichverteilten Zufallszahlen im Intervall [0,1] verteilt auf 100 Klassen." width="672" />
<p class="caption">
Figure 2.12: Histogramm von 100.000 gleichverteilten Zufallszahlen im Intervall [0,1] verteilt auf 100 Klassen.
</p>
</div>

<p>Auch hier sieht man, dass die erzeugten Werte im Intervall [0,1] ziemlich gleichverteilt sind. Mit R kann man relativ leicht, komplexere statistische Tests durchführen, um die Güte der erzeugten zufälligen Werte im Vergleich zu den vorgegebenen Verteilungen zu bestimmen. Dazu sind aber umfangreichere statistische Kenntnisse erforderlich, die den Rahmen an dieser Stelle sprengen würden.</p>
<p>Um „zufällige“ Zahlen zu erzeugen, benutzt R intern einen Zufallszahlengenerator (<em>RNG</em>, <em>random number generator</em>), der beim Start mithilfe der aktuellen Systemzeit immer unterschiedlich (und scheinbar zufällig) initialisiert wird. Um jedoch reproduzierbare „zufällige“ Werte zu erhalten, muss der Zufallszahlengenerator mit einer festen Zahl initialisiert werden; genau dies leistet <code>set.seed()</code>:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="ersteschritte.html#cb109-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb109-2"><a href="ersteschritte.html#cb109-2" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] -0.6264538  0.1836433 -0.8356286</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="ersteschritte.html#cb111-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb111-2"><a href="ersteschritte.html#cb111-2" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] -0.6264538  0.1836433 -0.8356286</code></pre>
</div>
<div id="skripte" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Skripte<a href="ersteschritte.html#skripte" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Befehle direkt in die Konsole einzugeben kann manchmal sehr hilfreich sein, aber spätestens, wenn man Ergebnisse reproduzieren oder die Herleitung der Ergebnisse dokumentieren will, ist es sinnvoller, mit Skripten zu arbeiten. R-Skripte sind einfache Textdateien mit der Endung „.R“, die R-Befehle und Kommentare enthalten. Im Folgenden werden wir auch nicht mehr von Befehlen sprechen, sondern den mehr oder weniger äquivalenten Begriff „<em>Anweisung</em>“ (engl.: statement) benutzen, der im Skript- und Programmierumfeld gebräuchlicher ist.</p>
<p>Abgesehen von kleinen Berechnungen zu Testzwecken und dem Aufrufen von Manual-Seiten sollten Sie im Folgenden fast immer Skripte benutzen!</p>
<p>Als integrierte Entwicklungsumgebung verfügt RStudio über einen Texteditor, mit dem Sie einfach Codebereiche an die Konsole schicken können. Wird ein Skript geladen, erscheint in RStudio ein zusätzlicher Bereich „Editor“, der den Texteditor enthält. RStudio wird beim Beenden automatisch alle offene Skripte speichern und beim erneuten Starten von RStudio werden die Skripte automatisch wieder geladen. Manuell können Sie über den Menüeintrag „File“ / „Open file …“ oder über „New File“ / „R Skript …“ ein Skript laden.</p>
<p>Wurde ein R-Skript geladen, können Sie nun Anweisungen und Kommentare verändern und einfügen. Mit der Tastenkombination <code>Strg-Enter</code> schicken Sie stets den kompletten Befehl, der durch die aktuelle Position des Cursors bestimmt ist, an die Konsole, wo er unmittelbar ausgeführt wird. In der Konsole erscheint sofort das Ergebnis. Mit <code>Strg-Shift-Enter</code> wird hingegen das gesamte Skript in der Konsole ausgeführt. Alternativ können Sie auch die entsprechenden Menü-Icons benutzen. Den Umgang mit Skripten werden Sie in der Übungsaufgabe 1 dieses Kapitels üben.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-39"></span>
<img src="gfx/abb13.png" alt="Befehlsausführung im RStudio-Texteditor." width="60%" />
<p class="caption">
Figure 2.13: Befehlsausführung im RStudio-Texteditor.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-40"></span>
<img src="gfx/abb14.png" alt="Zusätzlicher Editor-Bereich in R-Studio." width="100%" />
<p class="caption">
Figure 2.14: Zusätzlicher Editor-Bereich in R-Studio.
</p>
</div>
</div>
<div id="einführung-in-die-entwicklungsumgebung-von-r-fortgeschritten" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Einführung in die Entwicklungsumgebung von R (fortgeschritten)<a href="#einf%C3%BChrung-in-die-entwicklungsumgebung-von-r-fortgeschritten" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nachdem Sie mit viel Mühe und Zeit ein R-Skript erstellt haben, stellen Sie fest, dass das Ergebnis nicht dem entspricht, das Sie erwartet haben. Was tun Sie nun?</p>
<p>In diesem Abschnitt sind einige Tipps angeführt, wie Sie Ihre Skripte auf mögliche Fehler kontrollieren und diese ggf. identifizieren können.</p>
<p>Wir wollen dies anhand folgenden Codes bzw. Problems beispielhaft illustrieren:</p>
<p>Die Aufgabe besteht darin, für jedes Element des Vektors <code>xs</code> die quadrierte Abweichung vom Mittelwert zu bestimmen. Folglich wird als Ergebnis ein Vektor erwartet, den wir <code>v</code> nennen.</p>
<p>Wird der folgende Code ausgeführt, erhalten wir allerdings keinen Vektor, sondern nur einen Wert. Wo liegt der Fehler?</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="ersteschritte.html#cb113-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb113-2"><a href="ersteschritte.html#cb113-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span></span>
<span id="cb113-3"><a href="ersteschritte.html#cb113-3" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">sample</span>(x, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb113-4"><a href="ersteschritte.html#cb113-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(xs)</span>
<span id="cb113-5"><a href="ersteschritte.html#cb113-5" tabindex="-1"></a>xquer <span class="ot">&lt;-</span> <span class="fu">mean</span>(xs)</span>
<span id="cb113-6"><a href="ersteschritte.html#cb113-6" tabindex="-1"></a></span>
<span id="cb113-7"><a href="ersteschritte.html#cb113-7" tabindex="-1"></a><span class="co"># quadrierte Abweichung vom Mittelwert</span></span>
<span id="cb113-8"><a href="ersteschritte.html#cb113-8" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb113-9"><a href="ersteschritte.html#cb113-9" tabindex="-1"></a><span class="cf">for</span>(idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb113-10"><a href="ersteschritte.html#cb113-10" tabindex="-1"></a>  y <span class="ot">&lt;-</span> (xs[idx] <span class="sc">-</span> xquer)<span class="sc">^</span><span class="dv">2</span> </span>
<span id="cb113-11"><a href="ersteschritte.html#cb113-11" tabindex="-1"></a>  v <span class="ot">&lt;-</span> y </span>
<span id="cb113-12"><a href="ersteschritte.html#cb113-12" tabindex="-1"></a>}</span>
<span id="cb113-13"><a href="ersteschritte.html#cb113-13" tabindex="-1"></a></span>
<span id="cb113-14"><a href="ersteschritte.html#cb113-14" tabindex="-1"></a>v</span></code></pre></div>
<pre><code>## [1] 64872.09</code></pre>
<p><strong>Tipps zur Fehleridentifizierung:</strong></p>
<ol style="list-style-type: decimal">
<li>Oft haben Sie mehrere R-Skripte parallel oder seriell geöffnet. Folglich kann es sein, dass in Ihrer <em>Environment</em> (<em>Umgebung</em>) bereits einige Objekte definiert sind. Um zu kontrollieren, ob Objekte <em>einfach nur</em> überschrieben wurden und der Fehler möglicherweise gar nicht in Ihrem Skript bzw. in Ihrer Programmierung liegt, leeren Sie die <em>Environment</em> und führen Sie Ihr Skript bzw. Ihren Code erneut aus: Klicken Sie dafür auf das <em>Besen</em>-Symbol (in Abbildung <a href="ersteschritte.html#fig:abb-workspace">2.15</a> orange umrandet) (<em>Clear objects from the workspace</em>). Bestätigen Sie die anschließende Meldung mit “Yes” und Ihre <em>Environment</em> ist leer. Führen Sie Ihr Skript erneut aus.</li>
</ol>
<div class="figure"><span style="display:block;" id="fig:abb-workspace"></span>
<img src="gfx/abb_clear_workspace.PNG" alt="Workspace bzw. Environment leeren." width="60%" />
<p class="caption">
Figure 2.15: Workspace bzw. Environment leeren.
</p>
</div>
<p>In unserem Beispiel hat das Leeren der <em>Environment</em> und das erneute Ausführen des Skripts zu keiner Fehlerbehebung geführt.</p>
<ol start="2" style="list-style-type: decimal">
<li>Wir vermuten, dass der Fehler innerhalb der <code>for</code>-Schleife liegt. Folglich würde es uns helfen, wenn wir die Schleife schrittweise durchlaufen und überprüfen würden. Dies erreichen wir, indem wir einen <em>Breakpoint</em> in unserer Schleife z.B. mittels <code>browser()</code> wie folgt setzen <span class="citation">(<a href="#ref-McPherson2022">McPherson 2022</a>)</span>:</li>
</ol>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="ersteschritte.html#cb115-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb115-2"><a href="ersteschritte.html#cb115-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span></span>
<span id="cb115-3"><a href="ersteschritte.html#cb115-3" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">sample</span>(x, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb115-4"><a href="ersteschritte.html#cb115-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(xs)</span>
<span id="cb115-5"><a href="ersteschritte.html#cb115-5" tabindex="-1"></a>xquer <span class="ot">&lt;-</span> <span class="fu">mean</span>(xs)</span>
<span id="cb115-6"><a href="ersteschritte.html#cb115-6" tabindex="-1"></a></span>
<span id="cb115-7"><a href="ersteschritte.html#cb115-7" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb115-8"><a href="ersteschritte.html#cb115-8" tabindex="-1"></a><span class="cf">for</span>(idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb115-9"><a href="ersteschritte.html#cb115-9" tabindex="-1"></a>  <span class="fu">browser</span>() <span class="co"># Breakpoint setzen</span></span>
<span id="cb115-10"><a href="ersteschritte.html#cb115-10" tabindex="-1"></a>  y <span class="ot">&lt;-</span> (xs[idx] <span class="sc">-</span> xquer)<span class="sc">^</span><span class="dv">2</span> </span>
<span id="cb115-11"><a href="ersteschritte.html#cb115-11" tabindex="-1"></a>  v <span class="ot">&lt;-</span> y </span>
<span id="cb115-12"><a href="ersteschritte.html#cb115-12" tabindex="-1"></a>}</span>
<span id="cb115-13"><a href="ersteschritte.html#cb115-13" tabindex="-1"></a></span>
<span id="cb115-14"><a href="ersteschritte.html#cb115-14" tabindex="-1"></a>v</span></code></pre></div>
<p>Das im Folgenden beschriebene Vorgehen sowie weitere hilfreiche Tipps und Alternativen zum Thema <em>Debugging</em> sind <span class="citation">McPherson (<a href="#ref-McPherson2022">2022</a>)</span> zu entnehmen.
Klicken wir dann auf <em>Source</em>, wird die Funktion <code>browser()</code> gelb markiert und ein grüner Pfeil erscheint am linken Rand:</p>
<div class="figure"><span style="display:block;" id="fig:abb-debug1"></span>
<img src="gfx/abb_browser_function.PNG" alt="Debugging mithilfe der Funktion browser()." width="100%" />
<p class="caption">
Figure 2.16: Debugging mithilfe der Funktion <code>browser()</code>.
</p>
</div>

<p>Darüber hinaus</p>
<ul>
<li><p>öffnet sich ein Feld namens <em>Traceback</em> und</p></li>
<li><p>in der Konsole erscheint eine Leiste mit Optionen wie <em>Next</em>, <em>Stop</em> etc., die uns den <em>Debugging-Modus</em> anzeigen.</p></li>
</ul>
<p>Die einfachste Möglichkeit, um die <code>for</code>-Schleife schrittweise zu durchlaufen, besteht im Drücken der <code>Enter</code>-Taste. Dadurch <em>wandern</em> das gelbe Feld und der grüne Pfeil nach unten, d.h. in die nächste Code-Zeile. Auf die Werte der Variablen - in unserem Beispiel <code>idx</code>, <code>y</code> und <code>v</code> - kann zugegriffen werden, indem diese über die <em>Console</em> abgefragt über die <em>Environment</em> mitverfolgt werden (siehe Abbildung <a href="ersteschritte.html#fig:abb-debug2">2.17</a>). In der Abbildung <a href="ersteschritte.html#fig:abb-debug2">2.17</a> wurde die Schleife ein Mal vollständig durchlaufen, sodass <code>idx</code> nun den Wert <code>2</code> annimmt (siehe <em>Environment</em>).</p>
<div class="figure"><span style="display:block;" id="fig:abb-debug2"></span>
<img src="gfx/abb_browser_function2.PNG" alt="Vollständiges Durchlaufen der for-Schleife für idx = 1 und Zugriff auf die Zwischenwerte, die die Variablen idx, y und v annehmen." width="100%" />
<p class="caption">
Figure 2.17: Vollständiges Durchlaufen der <code>for</code>-Schleife für <code>idx = 1</code> und Zugriff auf die Zwischenwerte, die die Variablen <code>idx</code>, <code>y</code> und <code>v</code> annehmen.
</p>
</div>

<p>Weiterhin sehen wir in der Abbildung <a href="ersteschritte.html#fig:abb-debug2">2.17</a>, dass <code>v</code> aus einem Wert besteht, was wir erwarten, da bislang nur die quadratische Abweichung vom Mittelwert des ersten Elements des Vektors <code>xs</code> bestimmt wurde. Die Werte <code>v</code> und <code>y</code> sind somit identisch.</p>
<p>Durchlaufen wir die Schleife ein weiteres Mal (siehe Abbildung <a href="ersteschritte.html#fig:abb-debug3">2.18</a>) sehen wir erneut, dass <code>v</code> und <code>y</code> identisch sind, wohingegen wir erwarten würden, dass <code>v</code> nun zwei Werte enthält, da wir die quadratische Abweichung vom Mittelwert bislang für zwei Werte bestimmt haben.</p>
<div class="figure"><span style="display:block;" id="fig:abb-debug3"></span>
<img src="gfx/abb_browser_function3.PNG" alt="Vollständiges Durchlaufen der for-Schleife für idx = 1 und idx = 2 und Zugriff auf die Zwischenwerte, die die Variablen idx, y und v annehmen." width="100%" />
<p class="caption">
Figure 2.18: Vollständiges Durchlaufen der <code>for</code>-Schleife für <code>idx = 1</code> und <code>idx = 2</code> und Zugriff auf die Zwischenwerte, die die Variablen <code>idx</code>, <code>y</code> und <code>v</code> annehmen.
</p>
</div>

<p>Daraus können wir schließen, dass der Vektor <code>v</code> <strong>nicht</strong> nach jedem Durchlauf der <code>for</code>-Schleife <em>verlängert</em> wird, weshalb wir den Code wie folgt abändern müssen:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="ersteschritte.html#cb116-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb116-2"><a href="ersteschritte.html#cb116-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span></span>
<span id="cb116-3"><a href="ersteschritte.html#cb116-3" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">sample</span>(x, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb116-4"><a href="ersteschritte.html#cb116-4" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(xs)</span>
<span id="cb116-5"><a href="ersteschritte.html#cb116-5" tabindex="-1"></a>xquer <span class="ot">&lt;-</span> <span class="fu">mean</span>(xs)</span>
<span id="cb116-6"><a href="ersteschritte.html#cb116-6" tabindex="-1"></a></span>
<span id="cb116-7"><a href="ersteschritte.html#cb116-7" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb116-8"><a href="ersteschritte.html#cb116-8" tabindex="-1"></a><span class="cf">for</span>(idx <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb116-9"><a href="ersteschritte.html#cb116-9" tabindex="-1"></a>  y <span class="ot">&lt;-</span> (xs[idx] <span class="sc">-</span> xquer)<span class="sc">^</span><span class="dv">2</span> </span>
<span id="cb116-10"><a href="ersteschritte.html#cb116-10" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">c</span>(v, y) </span>
<span id="cb116-11"><a href="ersteschritte.html#cb116-11" tabindex="-1"></a>}</span>
<span id="cb116-12"><a href="ersteschritte.html#cb116-12" tabindex="-1"></a></span>
<span id="cb116-13"><a href="ersteschritte.html#cb116-13" tabindex="-1"></a>v</span></code></pre></div>
<p>Für einige mag das Problem bei diesem Code vielleicht sofort offensichtlich gewesen sein. Liegt jedoch ein deutlich umfangreicherer Code vor, so ist dieses Problem nicht sofort offensichtlich und <em>Debugging</em> ist nicht mehr wegzudenken.</p>
<p>Soll der <em>Debugging</em>-Modus beendet werden, kann entweder auf <em>Stop</em> (siehe Abbildung <a href="ersteschritte.html#fig:abb-debug2">2.17</a>) geklickt oder die <code>Esc</code> genutzt werden.</p>
<p><strong>Kurzzusammenfassung</strong></p>
<blockquote>
<ul>
<li>Anweisung versus Befehl</li>
<li><code>Strg-Enter</code>: die aktuelle Anweisung zur Ausführung an die Konsole senden</li>
<li><code>Strg-Shift-Enter</code>: das gesamte Skript wird in der Konsole ausgeführt</li>
<li><code>summary()</code></li>
<li><code>plot()</code>, <code>boxplot()</code> und <code>hist()</code></li>
<li><code>rnorm()</code>, <code>runif()</code>, <code>dnorm()</code></li>
<li><code>set.seed()</code></li>
</ul>
</blockquote>
</div>
<div id="übungen-1" class="section level2 unnumbered hasAnchor">
<h2>Übungen<a href="#%C3%BCbungen-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Alle Aufgaben beziehen sich auf die Programmiersprache R! In den Übungen werden an manchen Stellen R-Funktionen benutzt, die im Skript nicht detailliert erläutert werden. Benutzen Sie deswegen ausgiebig die entsprechenden Manual-Einträge und Hilfe-Systeme.</p>
<div id="aufgabe-1" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 1<a href="ersteschritte.html#aufgabe-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Gegeben ist folgender Code:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="ersteschritte.html#cb117-1" tabindex="-1"></a><span class="co"># J. Willms, August 2019</span></span>
<span id="cb117-2"><a href="ersteschritte.html#cb117-2" tabindex="-1"></a><span class="co"># Skript: Programmierung für statistische Datenanalyse</span></span>
<span id="cb117-3"><a href="ersteschritte.html#cb117-3" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb117-4"><a href="ersteschritte.html#cb117-4" tabindex="-1"></a><span class="co"># Quelltexte: Kapitel 2</span></span>
<span id="cb117-5"><a href="ersteschritte.html#cb117-5" tabindex="-1"></a></span>
<span id="cb117-6"><a href="ersteschritte.html#cb117-6" tabindex="-1"></a><span class="co"># Ausgabe der Installationsverzeichnisse</span></span>
<span id="cb117-7"><a href="ersteschritte.html#cb117-7" tabindex="-1"></a>?<span class="fu">.libPaths</span>()         <span class="co"># siehe Kapitel 1</span></span>
<span id="cb117-8"><a href="ersteschritte.html#cb117-8" tabindex="-1"></a></span>
<span id="cb117-9"><a href="ersteschritte.html#cb117-9" tabindex="-1"></a></span>
<span id="cb117-10"><a href="ersteschritte.html#cb117-10" tabindex="-1"></a><span class="do">##########: Numerische Ausdrücke und Zuweisungen ####</span></span>
<span id="cb117-11"><a href="ersteschritte.html#cb117-11" tabindex="-1"></a><span class="dv">6</span><span class="sc">*</span><span class="dv">7</span></span>
<span id="cb117-12"><a href="ersteschritte.html#cb117-12" tabindex="-1"></a></span>
<span id="cb117-13"><a href="ersteschritte.html#cb117-13" tabindex="-1"></a><span class="st">&#39;*&#39;</span> (<span class="dv">6</span>,<span class="dv">7</span>)</span>
<span id="cb117-14"><a href="ersteschritte.html#cb117-14" tabindex="-1"></a></span>
<span id="cb117-15"><a href="ersteschritte.html#cb117-15" tabindex="-1"></a><span class="dv">2</span><span class="sc">^</span><span class="dv">10</span>   <span class="co"># 2 hoch 10</span></span>
<span id="cb117-16"><a href="ersteschritte.html#cb117-16" tabindex="-1"></a><span class="dv">10</span><span class="sc">/</span><span class="dv">3</span>   <span class="co"># ganzzahlige Division?</span></span>
<span id="cb117-17"><a href="ersteschritte.html#cb117-17" tabindex="-1"></a></span>
<span id="cb117-18"><a href="ersteschritte.html#cb117-18" tabindex="-1"></a></span>
<span id="cb117-19"><a href="ersteschritte.html#cb117-19" tabindex="-1"></a><span class="do">##########: Variablen  ####  </span></span>
<span id="cb117-20"><a href="ersteschritte.html#cb117-20" tabindex="-1"></a>res <span class="ot">=</span> <span class="dv">10</span><span class="sc">/</span><span class="dv">3</span>       <span class="co"># &#39;=&#39; sollte vermieden werden</span></span>
<span id="cb117-21"><a href="ersteschritte.html#cb117-21" tabindex="-1"></a></span>
<span id="cb117-22"><a href="ersteschritte.html#cb117-22" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="dv">10</span><span class="sc">/</span><span class="dv">3</span></span>
<span id="cb117-23"><a href="ersteschritte.html#cb117-23" tabindex="-1"></a>res</span>
<span id="cb117-24"><a href="ersteschritte.html#cb117-24" tabindex="-1"></a>name <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb117-25"><a href="ersteschritte.html#cb117-25" tabindex="-1"></a>name</span>
<span id="cb117-26"><a href="ersteschritte.html#cb117-26" tabindex="-1"></a>name <span class="ot">&lt;-</span> <span class="st">&quot;zehn&quot;</span></span>
<span id="cb117-27"><a href="ersteschritte.html#cb117-27" tabindex="-1"></a>name</span>
<span id="cb117-28"><a href="ersteschritte.html#cb117-28" tabindex="-1"></a></span>
<span id="cb117-29"><a href="ersteschritte.html#cb117-29" tabindex="-1"></a>Res <span class="ot">=</span> <span class="fl">1.4</span></span>
<span id="cb117-30"><a href="ersteschritte.html#cb117-30" tabindex="-1"></a>Res</span>
<span id="cb117-31"><a href="ersteschritte.html#cb117-31" tabindex="-1"></a>res</span>
<span id="cb117-32"><a href="ersteschritte.html#cb117-32" tabindex="-1"></a></span>
<span id="cb117-33"><a href="ersteschritte.html#cb117-33" tabindex="-1"></a></span>
<span id="cb117-34"><a href="ersteschritte.html#cb117-34" tabindex="-1"></a><span class="do">##########: Ein Vektor als einfacher Datensatz ####</span></span>
<span id="cb117-35"><a href="ersteschritte.html#cb117-35" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">11</span>,<span class="dv">13</span>,<span class="dv">17</span>,<span class="dv">19</span>,<span class="dv">23</span>,<span class="dv">29</span>)</span>
<span id="cb117-36"><a href="ersteschritte.html#cb117-36" tabindex="-1"></a>p</span>
<span id="cb117-37"><a href="ersteschritte.html#cb117-37" tabindex="-1"></a>p[<span class="dv">1</span>]</span>
<span id="cb117-38"><a href="ersteschritte.html#cb117-38" tabindex="-1"></a>p[<span class="dv">2</span>]</span>
<span id="cb117-39"><a href="ersteschritte.html#cb117-39" tabindex="-1"></a>p[<span class="dv">10</span>]</span>
<span id="cb117-40"><a href="ersteschritte.html#cb117-40" tabindex="-1"></a>p[<span class="dv">11</span>]</span>
<span id="cb117-41"><a href="ersteschritte.html#cb117-41" tabindex="-1"></a>p[<span class="dv">12</span>]</span>
<span id="cb117-42"><a href="ersteschritte.html#cb117-42" tabindex="-1"></a>p[<span class="dv">13</span>]</span>
<span id="cb117-43"><a href="ersteschritte.html#cb117-43" tabindex="-1"></a>p[<span class="dv">13</span>] <span class="ot">&lt;-</span> <span class="dv">41</span></span>
<span id="cb117-44"><a href="ersteschritte.html#cb117-44" tabindex="-1"></a></span>
<span id="cb117-45"><a href="ersteschritte.html#cb117-45" tabindex="-1"></a>p</span>
<span id="cb117-46"><a href="ersteschritte.html#cb117-46" tabindex="-1"></a>p<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb117-47"><a href="ersteschritte.html#cb117-47" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span>p<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb117-48"><a href="ersteschritte.html#cb117-48" tabindex="-1"></a>p<span class="sc">%%</span><span class="dv">4</span></span>
<span id="cb117-49"><a href="ersteschritte.html#cb117-49" tabindex="-1"></a></span>
<span id="cb117-50"><a href="ersteschritte.html#cb117-50" tabindex="-1"></a><span class="fu">mean</span>(p)</span>
<span id="cb117-51"><a href="ersteschritte.html#cb117-51" tabindex="-1"></a><span class="fu">sd</span>(p)            </span>
<span id="cb117-52"><a href="ersteschritte.html#cb117-52" tabindex="-1"></a></span>
<span id="cb117-53"><a href="ersteschritte.html#cb117-53" tabindex="-1"></a><span class="fu">mean</span>(p, <span class="at">na.rm=</span><span class="cn">TRUE</span>)    <span class="co"># rm steht f?r remove</span></span>
<span id="cb117-54"><a href="ersteschritte.html#cb117-54" tabindex="-1"></a><span class="fu">sd</span>(p, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb117-55"><a href="ersteschritte.html#cb117-55" tabindex="-1"></a></span>
<span id="cb117-56"><a href="ersteschritte.html#cb117-56" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span></span>
<span id="cb117-57"><a href="ersteschritte.html#cb117-57" tabindex="-1"></a><span class="fu">sqrt</span>(x)</span>
<span id="cb117-58"><a href="ersteschritte.html#cb117-58" tabindex="-1"></a></span>
<span id="cb117-59"><a href="ersteschritte.html#cb117-59" tabindex="-1"></a></span>
<span id="cb117-60"><a href="ersteschritte.html#cb117-60" tabindex="-1"></a><span class="do">##########: Recycling ####</span></span>
<span id="cb117-61"><a href="ersteschritte.html#cb117-61" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">6</span>) <span class="co"># entspricht c(1,1,1,1,1,1)</span></span>
<span id="cb117-62"><a href="ersteschritte.html#cb117-62" tabindex="-1"></a>x</span>
<span id="cb117-63"><a href="ersteschritte.html#cb117-63" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)</span>
<span id="cb117-64"><a href="ersteschritte.html#cb117-64" tabindex="-1"></a>x<span class="sc">+</span>y</span>
<span id="cb117-65"><a href="ersteschritte.html#cb117-65" tabindex="-1"></a> </span>
<span id="cb117-66"><a href="ersteschritte.html#cb117-66" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>) <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span>
<span id="cb117-67"><a href="ersteschritte.html#cb117-67" tabindex="-1"></a></span>
<span id="cb117-68"><a href="ersteschritte.html#cb117-68" tabindex="-1"></a>?rep</span>
<span id="cb117-69"><a href="ersteschritte.html#cb117-69" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">6</span>)</span>
<span id="cb117-70"><a href="ersteschritte.html#cb117-70" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>   <span class="co"># wie c(1L,2L, 3L, 4L)</span></span>
<span id="cb117-71"><a href="ersteschritte.html#cb117-71" tabindex="-1"></a><span class="fu">str</span>(y)</span>
<span id="cb117-72"><a href="ersteschritte.html#cb117-72" tabindex="-1"></a>x<span class="sc">+</span>y</span>
<span id="cb117-73"><a href="ersteschritte.html#cb117-73" tabindex="-1"></a></span>
<span id="cb117-74"><a href="ersteschritte.html#cb117-74" tabindex="-1"></a><span class="fu">rep_len</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb117-75"><a href="ersteschritte.html#cb117-75" tabindex="-1"></a><span class="fu">rep_len</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">7</span>)</span>
<span id="cb117-76"><a href="ersteschritte.html#cb117-76" tabindex="-1"></a></span>
<span id="cb117-77"><a href="ersteschritte.html#cb117-77" tabindex="-1"></a><span class="fl">7.1</span><span class="sc">:</span><span class="fl">3.3</span> </span>
<span id="cb117-78"><a href="ersteschritte.html#cb117-78" tabindex="-1"></a><span class="dv">2</span><span class="sc">:</span><span class="dv">5</span> <span class="sc">+</span> <span class="dv">10</span></span>
<span id="cb117-79"><a href="ersteschritte.html#cb117-79" tabindex="-1"></a>?Syntax</span>
<span id="cb117-80"><a href="ersteschritte.html#cb117-80" tabindex="-1"></a></span>
<span id="cb117-81"><a href="ersteschritte.html#cb117-81" tabindex="-1"></a></span>
<span id="cb117-82"><a href="ersteschritte.html#cb117-82" tabindex="-1"></a><span class="do">##########: Mehr zu RStudio ####</span></span>
<span id="cb117-83"><a href="ersteschritte.html#cb117-83" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4</span><span class="sc">*</span>pi, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb117-84"><a href="ersteschritte.html#cb117-84" tabindex="-1"></a>x</span>
<span id="cb117-85"><a href="ersteschritte.html#cb117-85" tabindex="-1"></a></span>
<span id="cb117-86"><a href="ersteschritte.html#cb117-86" tabindex="-1"></a><span class="fu">help</span>(seq)</span>
<span id="cb117-87"><a href="ersteschritte.html#cb117-87" tabindex="-1"></a>?seq</span>
<span id="cb117-88"><a href="ersteschritte.html#cb117-88" tabindex="-1"></a></span>
<span id="cb117-89"><a href="ersteschritte.html#cb117-89" tabindex="-1"></a><span class="fu">str</span>(x)</span>
<span id="cb117-90"><a href="ersteschritte.html#cb117-90" tabindex="-1"></a><span class="co">#plot(x, sin(x))</span></span>
<span id="cb117-91"><a href="ersteschritte.html#cb117-91" tabindex="-1"></a><span class="fu">plot</span>(x, <span class="fu">sin</span>(x), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>) </span>
<span id="cb117-92"><a href="ersteschritte.html#cb117-92" tabindex="-1"></a></span>
<span id="cb117-93"><a href="ersteschritte.html#cb117-93" tabindex="-1"></a></span>
<span id="cb117-94"><a href="ersteschritte.html#cb117-94" tabindex="-1"></a><span class="do">##########: Demos ####</span></span>
<span id="cb117-95"><a href="ersteschritte.html#cb117-95" tabindex="-1"></a><span class="fu">demo</span>()</span>
<span id="cb117-96"><a href="ersteschritte.html#cb117-96" tabindex="-1"></a>Nile</span>
<span id="cb117-97"><a href="ersteschritte.html#cb117-97" tabindex="-1"></a><span class="fu">str</span>(Nile)</span>
<span id="cb117-98"><a href="ersteschritte.html#cb117-98" tabindex="-1"></a></span>
<span id="cb117-99"><a href="ersteschritte.html#cb117-99" tabindex="-1"></a><span class="fu">mean</span>(Nile)</span>
<span id="cb117-100"><a href="ersteschritte.html#cb117-100" tabindex="-1"></a><span class="fu">sd</span>(Nile)</span>
<span id="cb117-101"><a href="ersteschritte.html#cb117-101" tabindex="-1"></a><span class="fu">summary</span>(Nile)</span>
<span id="cb117-102"><a href="ersteschritte.html#cb117-102" tabindex="-1"></a><span class="fu">plot</span>(Nile)</span>
<span id="cb117-103"><a href="ersteschritte.html#cb117-103" tabindex="-1"></a><span class="fu">hist</span>(Nile)</span>
<span id="cb117-104"><a href="ersteschritte.html#cb117-104" tabindex="-1"></a><span class="fu">boxplot</span>(Nile) </span>
<span id="cb117-105"><a href="ersteschritte.html#cb117-105" tabindex="-1"></a></span>
<span id="cb117-106"><a href="ersteschritte.html#cb117-106" tabindex="-1"></a><span class="do">##########: </span></span>
<span id="cb117-107"><a href="ersteschritte.html#cb117-107" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb117-108"><a href="ersteschritte.html#cb117-108" tabindex="-1"></a><span class="fu">runif</span>(<span class="dv">10</span>)</span>
<span id="cb117-109"><a href="ersteschritte.html#cb117-109" tabindex="-1"></a></span>
<span id="cb117-110"><a href="ersteschritte.html#cb117-110" tabindex="-1"></a>?runif</span>
<span id="cb117-111"><a href="ersteschritte.html#cb117-111" tabindex="-1"></a></span>
<span id="cb117-112"><a href="ersteschritte.html#cb117-112" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000</span>)</span>
<span id="cb117-113"><a href="ersteschritte.html#cb117-113" tabindex="-1"></a><span class="fu">summary</span>(y)</span>
<span id="cb117-114"><a href="ersteschritte.html#cb117-114" tabindex="-1"></a></span>
<span id="cb117-115"><a href="ersteschritte.html#cb117-115" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1000000</span>)</span>
<span id="cb117-116"><a href="ersteschritte.html#cb117-116" tabindex="-1"></a><span class="fu">summary</span>(x)</span>
<span id="cb117-117"><a href="ersteschritte.html#cb117-117" tabindex="-1"></a></span>
<span id="cb117-118"><a href="ersteschritte.html#cb117-118" tabindex="-1"></a><span class="fu">hist</span>(y)</span>
<span id="cb117-119"><a href="ersteschritte.html#cb117-119" tabindex="-1"></a><span class="fu">hist</span>(x, <span class="at">breaks =</span> <span class="dv">100</span>)</span>
<span id="cb117-120"><a href="ersteschritte.html#cb117-120" tabindex="-1"></a></span>
<span id="cb117-121"><a href="ersteschritte.html#cb117-121" tabindex="-1"></a></span>
<span id="cb117-122"><a href="ersteschritte.html#cb117-122" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000</span>)</span>
<span id="cb117-123"><a href="ersteschritte.html#cb117-123" tabindex="-1"></a><span class="fu">summary</span>(y)</span>
<span id="cb117-124"><a href="ersteschritte.html#cb117-124" tabindex="-1"></a></span>
<span id="cb117-125"><a href="ersteschritte.html#cb117-125" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000000</span>)</span>
<span id="cb117-126"><a href="ersteschritte.html#cb117-126" tabindex="-1"></a><span class="fu">summary</span>(x)</span>
<span id="cb117-127"><a href="ersteschritte.html#cb117-127" tabindex="-1"></a></span>
<span id="cb117-128"><a href="ersteschritte.html#cb117-128" tabindex="-1"></a><span class="fu">hist</span>(y)</span>
<span id="cb117-129"><a href="ersteschritte.html#cb117-129" tabindex="-1"></a><span class="fu">hist</span>(x, <span class="at">breaks =</span> <span class="dv">100</span>)</span>
<span id="cb117-130"><a href="ersteschritte.html#cb117-130" tabindex="-1"></a></span>
<span id="cb117-131"><a href="ersteschritte.html#cb117-131" tabindex="-1"></a> </span>
<span id="cb117-132"><a href="ersteschritte.html#cb117-132" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb117-133"><a href="ersteschritte.html#cb117-133" tabindex="-1"></a><span class="fu">plot</span>(z, <span class="dv">100000</span><span class="sc">*</span><span class="fu">dnorm</span>(z), <span class="at">type=</span><span class="st">&quot;l&quot;</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb117-134"><a href="ersteschritte.html#cb117-134" tabindex="-1"></a></span>
<span id="cb117-135"><a href="ersteschritte.html#cb117-135" tabindex="-1"></a></span>
<span id="cb117-136"><a href="ersteschritte.html#cb117-136" tabindex="-1"></a><span class="do">##########: RNG ####</span></span>
<span id="cb117-137"><a href="ersteschritte.html#cb117-137" tabindex="-1"></a>?set.seed</span>
<span id="cb117-138"><a href="ersteschritte.html#cb117-138" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb117-139"><a href="ersteschritte.html#cb117-139" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb117-140"><a href="ersteschritte.html#cb117-140" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb117-141"><a href="ersteschritte.html#cb117-141" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb117-142"><a href="ersteschritte.html#cb117-142" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb117-143"><a href="ersteschritte.html#cb117-143" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb117-144"><a href="ersteschritte.html#cb117-144" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span>
<span id="cb117-145"><a href="ersteschritte.html#cb117-145" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">3</span>)</span></code></pre></div>
<ol style="list-style-type: lower-alpha">
<li><p>Speichern Sie diesen Code in Form eines Skripts und führen Sie es anschließend schrittweise aus. Ergänzen Sie Kommentare.</p></li>
<li><p>Erstellen Sie ein Skript „01_ersteBeispiele2.R“, indem Sie das Skript aus Aufgabenteil a) leicht abwandeln. Untersuchen Sie, wie im Editor Fehler unmittelbar angezeigt werden und testen Sie die <em>Autovervollständigung</em> in der Konsole und im Editor.</p></li>
</ol>
</div>
<div id="aufgabe-2" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 2<a href="ersteschritte.html#aufgabe-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Erstellen Sie im RStudio ein Projekt „psd_1“ in einem neu zu erstellenden Verzeichnis „psd_1“. Alle relevanten Quelldateien für den ersten Teil des Skripts und der entsprechenden Übungen sollen in Ihrem Verzeichnis „psd_1“ gespeichert sein.</p>
</div>
<div id="aufgabe-3" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 3<a href="ersteschritte.html#aufgabe-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: lower-alpha">
<li><p>Welchen Wert haben folgende Anweisungen?</p>
<table>
<thead>
<tr class="header">
<th>Anweisung</th>
<th>Wert (Antwort)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>1 / 0</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>0 / 0</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>1 / 0 - 1 / 0</code></td>
<td></td>
</tr>
<tr class="even">
<td>Was ist der Unterschied zwischen <code>Inf</code> und <code>NaN</code>? (siehe <code>?NaN</code>)</td>
<td></td>
</tr>
<tr class="odd">
<td><code>47 %% 10</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>47 %/% 10</code></td>
<td></td>
</tr>
<tr class="odd">
<td>(Hinweis: siehe <code>?'%/%'</code>)</td>
<td></td>
</tr>
<tr class="even">
<td><code>-9 %% 5</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>-11 %% 5</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>3.1 %% 3</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>pi %% 3</code></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>factorial(5)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>factorial(60)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>abs(-3)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>choose(4,2)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>choose(6,1)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>choose(6,2)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>choose(6,3)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>choose(6,4)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>choose(49,6)</code></td>
<td></td>
</tr>
<tr class="even">
<td>Was hat der letzte Ausdruck mit Lotto zu tun?</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>x &lt;- 1:6</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>tan(atan(x))</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>log(exp(x))</code></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Wenn <code>x &lt;- c(2,3,5,2)</code>, was wird ausgegeben und wieso? Erstellen Sie zusätzlich eine kurze Beschreibung der Funktionen.</p>
<table>
<thead>
<tr class="header">
<th>Anweisung</th>
<th>Wert und Antwort</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sum(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>prod(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>cumsum(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>cumprod(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>diff(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>min(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>max(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>range(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sort(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>mean(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>var(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sd(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
</tr>
<tr class="even">
<td><code>x %% 5</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>x %% 5 - 3</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>x + c(1,2)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>x + 1:8</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>8:4</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>3.8 : 7.2</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>7.2 : 3.8</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>rep(x,3)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>x &lt;- c(2,3,5,2)</code>; <code>x[6] &lt;- 10</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>x</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sum(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>sum(x, na.rm = TRUE)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>mean(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>mean(p, na.rm = TRUE)</code></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Gegeben ist:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="ersteschritte.html#cb118-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>)</span>
<span id="cb118-2"><a href="ersteschritte.html#cb118-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dv">7</span>) </span>
<span id="cb118-3"><a href="ersteschritte.html#cb118-3" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">c</span>(x, y, <span class="dv">17</span>)</span>
<span id="cb118-4"><a href="ersteschritte.html#cb118-4" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">c</span>(z, z)</span></code></pre></div>
<p>Was wird ausgegeben und wieso?</p>
<ul>
<li><code>x</code></li>
<li><code>y</code></li>
<li><code>length(z)</code></li>
</ul></li>
<li><p>Vervollständigen Sie die folgenden beiden Tabellen, die eine kurze Zusammenfassung kennengelernter R-Funktionen geben.</p>
<p><em>Elementare Funktionen:</em></p>
<table>
<thead>
<tr class="header">
<th>Funktion</th>
<th>Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>abs(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>choose(n,k)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>factorial(n)</code></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><code>log(x)</code></td>
<td>natürlicher Logarithmus von x</td>
</tr>
<tr class="even">
<td><code>log10(x)</code></td>
<td>Logarithmus von x zur Basis 10</td>
</tr>
<tr class="odd">
<td><code>exp(x)</code></td>
<td>Exponentialfunktion angewandt auf x</td>
</tr>
<tr class="even">
<td><code>sin(x)</code></td>
<td>Sinus von x</td>
</tr>
<tr class="odd">
<td><code>cos(x)</code></td>
<td>Kosinus von x</td>
</tr>
<tr class="even">
<td><code>tan(x)</code></td>
<td>Tangens von x</td>
</tr>
<tr class="odd">
<td><code>asin(x)</code></td>
<td>Arkussinus von x</td>
</tr>
<tr class="even">
<td><code>acos(x)</code></td>
<td>Arkuskosinus von x</td>
</tr>
<tr class="odd">
<td><code>atan(x)</code></td>
<td>Arkustangens von x</td>
</tr>
</tbody>
</table>
<p><em>Funktionen für Vektoren <code>x</code>:</em></p>
<table>
<colgroup>
<col width="48%" />
<col width="52%" />
</colgroup>
<thead>
<tr class="header">
<th>Funktion</th>
<th>Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sort(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>length(x)</code></td>
<td>Anzahl der Elemente von <code>x</code></td>
</tr>
<tr class="odd">
<td><code>any(x,cond)</code></td>
<td><code>TRUE</code>, falls mindestens ein Element von <code>x</code> die übergebene Bedingung <code>cond</code> erfüllt</td>
</tr>
<tr class="even">
<td><code>all(x,cond)</code></td>
<td><code>TRUE</code>, falls alle Elemente von <code>x</code> die übergebene Bedingung <code>cond</code> erfüllen</td>
</tr>
<tr class="odd">
<td><code>min(x)</code></td>
<td>Minimum der Elemente von <code>x</code></td>
</tr>
<tr class="even">
<td><code>max(x)</code></td>
<td>Maximum der Elemente von <code>x</code></td>
</tr>
<tr class="odd">
<td><code>range(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sum(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>prod(x)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>cumsum(x)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>cumprod(x)</code></td>
<td></td>
</tr>
</tbody>
</table></li>
</ol>
</div>
<div id="aufgabe-4" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 4<a href="ersteschritte.html#aufgabe-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Gegeben ist ein numerischer Vektor wie z. B. <code>p &lt;- c(2,3,5,-7,11,13,17,19,-23,-29)</code> und<br />
<code>dp &lt;- diff(p)</code>. Wie kann man mithilfe von <code>dp</code> und <code>p[1]</code> in einer Anweisung die Werte von <code>p</code> wieder zurückgewinnen?</p>
</div>
<div id="aufgabe-5" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 5<a href="ersteschritte.html#aufgabe-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<thead>
<tr class="header">
<th>Funktionsaufruf von <code>sample()</code></th>
<th>Bedeutung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sample(x, k)</code></td>
<td>Zufällige Auswahl von <code>k</code> Elementen aus <code>x</code></td>
</tr>
<tr class="even">
<td><code>sample(x, k, TRUE)</code></td>
<td>(ohne und mit Zurücklegen)</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li><p>Gegeben ist <code>set.seed(1); x &lt;- 1:5</code>. Was gibt die Funktion <code>sample()</code> zurück?</p>
<table>
<thead>
<tr class="header">
<th>Aufruf der Funktion</th>
<th>Rückgabewert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>sample(5, 3)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sample(5, 3)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>sample(5, 5)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sample(5, 5)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>sample(5, 3, TRUE)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sample(5, 3, TRUE)</code></td>
<td></td>
</tr>
<tr class="odd">
<td><code>sample(5, 5, TRUE)</code></td>
<td></td>
</tr>
<tr class="even">
<td><code>sample(5, 5, TRUE)</code></td>
<td></td>
</tr>
</tbody>
</table></li>
<li><p>Erzeugen Sie eine zufällige Folge von Nullen und Einsen der Länge 1000 (HINWEIS: <code>sample()</code>).</p></li>
<li><p>Erzeugen Sie fünf Permutationen der Ziffern von 0 bis 9.</p></li>
</ol>
</div>
<div id="aufgabe-6" class="section level3 unnumbered hasAnchor">
<h3>Aufgabe 6<a href="ersteschritte.html#aufgabe-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(Random Walk, siehe auch: <a href="https://de.wikipedia.org/wiki/Random_Walk">https://de.wikipedia.org/wiki/Random_Walk</a>)</p>
<p>Ein Betrunkener läuft mit Wahrscheinlichkeit <span class="math inline">\(p=0.5\)</span> einen Schritt nach rechts und mit gleicher Wahrscheinlichkeit einen Schritt nach links. Die Schritte sind alle gleich lang und die Entscheidung, in welche Richtung er geht, hängt nicht von der Vergangenheit ab. Visualisieren Sie die Realisierung eines möglichen Wegs, der 100000 Schritte umfasst.</p>
<p>Eine Realisierung eines möglichen Wegs könnte wie folgt aussehen:</p>
<div class="figure"><span style="display:block;" id="fig:plot-random-walk"></span>
<img src="bchwtz-rprg_files/figure-html/plot-random-walk-1.png" alt="Randwom Walk - eine Realisierung eines möglichen Wegs." width="80%" />
<p class="caption">
Figure 2.19: Randwom Walk - eine Realisierung eines möglichen Wegs.
</p>
</div>

</div>
<div id="kurzzusammenfassung" class="section level3 unnumbered hasAnchor">
<h3>Kurzzusammenfassung<a href="ersteschritte.html#kurzzusammenfassung" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<ul>
<li><code>%/%</code></li>
<li><code>log()</code>, <code>log10()</code>, <code>exp()</code></li>
<li><code>sin()</code>, <code>cos()</code>, <code>tan()</code></li>
<li><code>asin()</code>, <code>acos()</code>, <code>atan()</code></li>
<li><code>abs()</code></li>
<li><code>choose(n,k)</code></li>
<li><code>factorial(n)</code></li>
<li><code>sort()</code><br />
</li>
<li><code>min()</code>, <code>max()</code>, <code>range()</code></li>
<li><code>sum()</code>, <code>prod()</code></li>
<li><code>cumsum()</code>, <code>cumprod()</code></li>
<li><code>sample()</code></li>
</ul>
</blockquote>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-McPherson2022" class="csl-entry">
McPherson, Jonathan. 2022. <span>“Debugging with the RStudio IDE.”</span> <a href="https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-the-RStudio-IDE">https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-the-RStudio-IDE</a>.
</div>
<div id="ref-datasets" class="csl-entry">
———. 2021. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="einführung.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-firststeps.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bchwtz-rprg.pdf", "bchwtz-rprg.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
